### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by ReneAMV** [cwi-reset/edicao-04-level-1#10]
E aí pessoal, me chamo Renê e sou formado em gastronomia a cerca de quatro anos e desde então venho trabalhando na área porém, quero migrar para TI onde me vejo com um futuro maior e tenho certeza de que o RESET é o programa certo para isso.

**Comment by gustavoullmann** [comment]
Oi @ReneAMV! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
