### ISSUE TITLE
REset

### ISSUE THREAD

**Issue by Danjr2022** [cwi-reset/edicao-04-level-1#101]
Bom dia. Contente em fazer parte dessa etapa. Sou o Daniel, estou vindo de outra carreira na ciência da informação, Disciplina de Arquivo e dando um RESET junto com a CWI, ansioso por essa migração de carreira.

**Comment by gustavoullmann** [comment]
Oi @Danjr2022! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
