### ISSUE TITLE
layllacastilho

### ISSUE THREAD

**Issue by LayllaCastilho** [cwi-reset/edicao-04-level-1#105]
Olá! Sou a Laylla, estou vindo de outra carreira na Enfermagem e dando um RESET junto com o CWI , muito feliz por estar aqui ❤️

**Comment by gustavoullmann** [comment]
Oi @LayllaCastilho! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
