### ISSUE TITLE
Apresentação!!!

### ISSUE THREAD

**Issue by AlexandreDChaves** [cwi-reset/edicao-04-level-1#106]
Ola, meu nome é Alexandre Chaves sou do RJ. Estou vindo da área de T.I mesmo,(Service Desk)
Estou tentando realizar a transição de carreira. Estou muito motivado pela oportunidade da CWI Reset.
Vamos pra cima!!

**Comment by gustavoullmann** [comment]
Oi @AlexandreDChaves! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
