### ISSUE TITLE
Obrigado pela oportunidade!

### ISSUE THREAD

**Issue by felipeeugeniopereira** [cwi-reset/edicao-04-level-1#107]
Olá galera, me chamo Felipe Eugênio, estou na área de fotografia há quase 10 anos, ansioso para aprender com vocês!

**Comment by gustavoullmann** [comment]
Oi @felipeeugeniopereira! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
