### ISSUE TITLE
Apresentação: Rafael Honesko Altismo

### ISSUE THREAD

**Issue by rhonesko** [cwi-reset/edicao-04-level-1#108]
Olá, me chamo Rafael Honesko Altismo, tenho 35 anos, trabalhava na siderurgica GERDAU na produção, estou tentando a migração de carreira, e com essa oportunidade incrivel pretendo me impenhar ao maximo .
O que eu puder ajudar alguem e ser ajudado vou ficar muito feliz e satisfeito, então deixo meu olá e vamos todos juntos...

**Comment by gustavoullmann** [comment]
Oi @rhonesko! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
