### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by KetlenAlmeida** [cwi-reset/edicao-04-level-1#109]
Olá,
Meu nome é Ketlen Almeida, sou professora concursada no município de Sapiranga. 
Estou feliz  pela oportunidade de poder começar em uma nova área e transformar minha carreira.

**Comment by gustavoullmann** [comment]
Oi @KetlenAlmeida! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
