### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by MaiqueMatheus** [cwi-reset/edicao-04-level-1#114]
Bom dia galera!!
Meu nome é Maique Matheus da Silva, tenho 29 anos, trabalho como instrutor de trânsito há 6 anos, e estou super enpolgado para esse novo desafio...
Boa sorte para todos..

**Comment by gustavoullmann** [comment]
Oi @MaiqueMatheus! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
