### ISSUE TITLE
Olá pessoal, me chamo Herlen, tenho 25 anos, sou de Campina Grande - PB.

### ISSUE THREAD

**Issue by herlenporto** [cwi-reset/edicao-04-level-1#115]
Me formei em Arquitetura e Urbanismo, estou fazendo minha transição de carreira, cursando ciências da computação e buscando minha primeira oportunidade na área! Vamos que vamos agarrar com tudo essa oportunidade do RESET e fazer dela a oportunidade de nossas vidas! Boa sorte a todos.

**Comment by gustavoullmann** [comment]
Oi @herlenporto! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
