### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by AlessandraFavila** [cwi-reset/edicao-04-level-1#118]
Olá pessoal! Sou Alessandra e atuo na área de administração, que é a minha formação. 
Estou buscando oportunidade na tecnologia. Feliz por estar neste processo! Bora resetar!

**Comment by gustavoullmann** [comment]
Oi @AlessandraFavila! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
