### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by Caroline170480** [cwi-reset/edicao-04-level-1#119]
Oi! Meu nome é Caroline Bittencourt Menezes e estou chegando para dar um Reset! Bora lá! Sou formada no Secretariado Executivo Trilíngue desde 2014, mas agora estou certa na carreira de TI .

**Comment by gustavoullmann** [comment]
Oi @Caroline170480! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by gustavoullmann** [comment]
Oi @Caroline170480! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
