### ISSUE TITLE
APRESENTAÇÃO 

### ISSUE THREAD

**Issue by Brunazordan** [cwi-reset/edicao-04-level-1#12]
Boa noite! Meu nome é Bruna Zordan, tenho 26 anos e trabalhei como operadora de pedágio por 7 anos e fazem 4 meses que resolvi dar um reset na carreira profissional.   Boa sorte a todos! 🚀

**Comment by Robertobarross** [comment]
Olá, pessoal! Tudo bem com vocês? Espero que sim!
Me chamo Roberto Barros, atualmente trabalho como Instrutor de Trânsito. A cerca de dois anos venho tentando entrar na área de tecnologia como Desenvolvedor. Vi no Reset uma ótima oportunidade, então, estou aqui! Vamos que vamos! Deus no comando...

Att, Roberto Barros.

**Comment by AndersonAJO** [comment]
Legal Roberto, é isso aí, vamos que vamos 👍

**Comment by Paulohack** [comment]
Bom dia, me chamo Paulo Inácio Hackenhaar, também sou instrutor de trânsito. Também me inscrevi, porque gosto de desafios, e entrar na área da tecnologia da informação,  é algo realmente desafiador. Então vamos arregassar as  mangas, sejam todos bem vindos, e contem comigo para a troca de idéias, sucesso a todos.

**Comment by Robertobarross** [comment]
Simbora, vamos pra cima! Tenham todos um final de semana abençoado.

**Comment by gustavoullmann** [comment]
Oi @Brunazordan, @Robertobarross, @Paulohack! Sejam bem vindos!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
