### ISSUE TITLE
[Apresentação] [CWI - Level 1]

### ISSUE THREAD

**Issue by daniellemmoura** [cwi-reset/edicao-04-level-1#120]
Bom dia pessoal!
Me chamo Danielle, sou do Rio de Janeiro e atualmente trabalho com testes manuais. Tenho 32 anos e amo aprender coisas novas. Adoro conhecer pessoas e poder trocar ideias. Contem comigo! 👍

**Comment by gustavoullmann** [comment]
Oi @daniellemmoura! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by Lauads** [comment]
Boa tarde,
Meu nome é Lauriana. Atuei como suporte especializado N2, e tenho muita vontade de migrar para QA.

**Comment by joprestes** [comment]
Oi @Lauads ! Sejam bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos 🚀
