### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by xMarcinha** [cwi-reset/edicao-04-level-1#121]
Olá, sou Marcia, tenho 25 anos, no momento estou morando em Portugal, mais sou do Interior de São Paulo e trabalhei por anos com atendimento ao público .. agora, eu quero me aventurar nessa área e estou ansiosa!

**Comment by gustavoullmann** [comment]
Oi @xMarcinha! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
