### ISSUE TITLE
Cwi - reset / edição 4 - level 1 #121

### ISSUE THREAD

**Issue by rafacarneiro86** [cwi-reset/edicao-04-level-1#122]
Olá a todos
Me chamo Rafael Ferreira Carneiro,sou de Cachoeirinha/RS.
Trabalho na área de pesquisas de mercado,e estou em transição para a área de TI.

**Comment by gustavoullmann** [comment]
Oi @rafacarneiro86! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by rafacarneiro86** [comment]
> Oi @rafacarneiro86! Seja bem vindo!
> A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1
> 
> Bons estudos :rocket:

Boa tarde,Gustavo. Obrigado pela dica 👊
