### ISSUE TITLE
Primeira Missão - CWI

### ISSUE THREAD

**Issue by paularosaa** [cwi-reset/edicao-04-level-1#123]
Oie! 
Me chamo Paula, sou recepcionista em uma clinica médica! 
Ansiosa por iniciar e dar um RESET na minha carreira! 
Obrigada CWI pela oportunidade!!!!
Boraaaa 🚀🚀

**Comment by KMSURFER** [comment]
Olá meu nome é Kleber , sou Mecânico e atuava em uma empresa terceirizada que fiscalizava os meios de transporte do estado de São Paulo .
E desde já agradeço a CWI por poder nos proporcionar essa transição de carreira !!!
