### ISSUE TITLE
Apresentação!

### ISSUE THREAD

**Issue by bragagiovani2** [cwi-reset/edicao-04-level-1#124]
Olá! Me chamo Giovani e venho da área de suporte, sou estudante de Análise e Desenvolvimento de Sistemas!
Bom RESET a todos nós!

**Comment by MichelGoncalves88** [comment]
Bom dia! Me chamo Michel Gonçalves. Sou técnico em mecânica industrial, porém no ano de 2021 resolvi começar a minha transição de carreira para a área de tecnologia da informação, começando a cursar faculdade de Análise e Desenvolvimento de Sistemas. Bom início de #reset a todos!!!

**Comment by joprestes** [comment]
Oi @bragagiovani2 e @MichelGoncalves88 ! Sejam bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: #1 

Bons estudos 🚀
