### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by Clarice1977** [cwi-reset/edicao-04-level-1#125]
Bom dia!
Me chamo Clarice Lemos Pereira,  sou Contadora. Graduada pela PUC. Tenho MBA em Gestão Financeira e Tributária.   Trabalho há quase 20 anos em uma Seguradora.  Tenho experiência na área Contábil e financeira.  E estou finalizando o 3° semestre de Gestão de TI. Espero aprender muito e compartilhar conhecimento! Obrigada pela oportunidade de poder fazer parte !

**Comment by gustavoullmann** [comment]
Oi @Clarice1977! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by Clarice1977** [comment]
Boa tarde,

Obrigada !
Coloquei de novo.

Em seg., 29 de ago. de 2022 13:24, Gustavo Ullmann ***@***.***>
escreveu:
