### ISSUE TITLE
Apresentação Bruna Araujo

### ISSUE THREAD

**Issue by Bru791** [cwi-reset/edicao-04-level-1#127]
Bom dia, galera. Meu nome é Bruna, tenho 25 anos. Trabalho na área administrativa há 3 anos, e sou formada há 1 ano. Boa sorte a todos!

**Comment by gustavoullmann** [comment]
Oi @Bru791! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
