### ISSUE TITLE
CWI Primeira Missão Reset ✅

### ISSUE THREAD

**Issue by KMSURFER** [cwi-reset/edicao-04-level-1#130]
Olá Meu nome é Kleber sou mecânico e estou em transição de carreira para área de tecnologia !!! 
Desde já agradeço a oportunidade da CWI por esse ótimo programa !!
Um forte abraço a todos !!!

**Comment by joprestes** [comment]
Oi  Kleber! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: #1 

Bons estudos🚀
