### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by Laurimiguel** [cwi-reset/edicao-04-level-1#134]
Boa tarde me Chamo Lauri e sou professor de educação física. Estou muito motivado para dar um reset na minha carreira!!!
Obrigado pela oportunidade CWI. Vamos nessa!!! Bom reset a todos!

**Comment by gustavoullmann** [comment]
Oi @Laurimiguel! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
