### ISSUE TITLE
RESET!!!!

### ISSUE THREAD

**Issue by ivandesiqueira** [cwi-reset/edicao-04-level-1#135]
Boa tarde , me chamo Ivan , tenho 33 anos e mora em Uberaba MG. Atualmente trabalho no setor industrial como torneiro mecânico e manutenção industrial. Bora dar um reset na carreira!!!

**Comment by gustavoullmann** [comment]
Oi @ivandesiqueira! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
