### ISSUE TITLE
BoniFelix

### ISSUE THREAD

**Issue by BoniFelix** [cwi-reset/edicao-04-level-1#137]
```Olá, me Chamem de Boni Felix, estou vindo da área de suprimentos e compras, administração e gestão. Mergulhando fundo no Reset!!! #vamoquevamo!```

**Comment by gustavoullmann** [comment]
Oi @BoniFelix! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
