### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by Clarice1977** [cwi-reset/edicao-04-level-1#138]
Bom dia!
Me chamo Clarice Lemos Pereira, sou Contadora. Graduada pela PUC. Tenho MBA em Gestão Financeira e Tributária. Trabalho há quase 20 anos em uma Seguradora. Tenho experiência na área Contábil e financeira. E estou finalizando o 3° semestre de Gestão de TI. Espero aprender muito e compartilhar conhecimento! Obrigada pela oportunidade de poder fazer parte !

**Comment by 89anderson** [comment]
Oi @Clarice1977 ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1 

Bons estudos🚀
