### ISSUE TITLE
Networking 

### ISSUE THREAD

**Issue by diegorafaelvieira** [cwi-reset/edicao-04-level-1#139]
Dei uma conferida e não encontrei nenhum tópico sobre isso e resolvi criá-lo.
Agradeço a Cwi e aos responsáveis pelo Reset por essa oportunidade. 
Segue o meu perfil na rede:
[LinkedIn](https://www.linkedin.com/in/diegorafaelvieira/)

**Comment by denise-muller** [comment]
Boa tarde, Diego! 
Já havia sido criada uma issue com esse assunto <a href="https://github.com/cwi-reset/edicao-04-level-1/issues/116">aqui</a>.

**Comment by diegorafaelvieira** [comment]
Obrigado @denise-muller já vou fechar aqui.
