### ISSUE TITLE
Olá pessoal!!!

### ISSUE THREAD

**Issue by POPIOLSKI** [cwi-reset/edicao-04-level-1#14]
Meu nome é  Aline Secco Popiolski e atuo na área do Direito! 
Estou imensamente feliz por fazer parte desta equipe CWI!!
Boa sorte a todos nós! 🚀

**Comment by gustavoullmann** [comment]
Oi @POPIOLSKI! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
