### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by wewdsilva** [cwi-reset/edicao-04-level-1#141]
Olá, me chamo Wellington, estou muito feliz em participar de processo do RESET, trabalho a mais de 10 ano como suporte técnico e estou agarrando essa oportunidade de da um RESET como profissional.

**Comment by 89anderson** [comment]
Oi @wewdsilva ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1 

Bons estudos🚀
