### ISSUE TITLE
Minha apresentação :)

### ISSUE THREAD

**Issue by Analarissalima** [cwi-reset/edicao-04-level-1#142]
### Oii, gente!! 
Me chamo Ana Larissa, sou farmacêutica, moro na Paraíba. Estou tentando migrar para a área de tecnologia. Muito feliz, grata e empolgada pela oportunidade. Que juntos possamos aprender muito e crescer. 😄

**Comment by 89anderson** [comment]
Oi @Analarissalima ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
