### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by ysabeella** [cwi-reset/edicao-04-level-1#143]
Oie pessoal! Sou a Ysabella Cristina A. Silva. Sou estudante de engenharia de automação e estagio na área. Atualmente estou migrando de automação para dev haha
Booora! 🤜🤛

**Comment by 89anderson** [comment]
Oi @ysabeella ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
