### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by MozanaMMMB** [cwi-reset/edicao-04-level-1#144]
Boa tarde!
Meu nome é Mozana, trabalhei como advogada nos últimos 5 anos. Estou pronta para dar um RESET  na minha carreira. Fiquei muito feliz por essa oportunidade. Partiu migrar!

**Comment by 89anderson** [comment]
Oi @MozanaMMMB ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
