### ISSUE TITLE
Apresentação :)

### ISSUE THREAD

**Issue by fingerfernanda** [cwi-reset/edicao-04-level-1#146]
Olá! Me chamo Fernanda, tenho 28 anos, atualmente cursando Marketing, mas minha vida profissional foi sempre em atendimento e nos ultimos anos, na área de desenvolvimento de materiais para calçados, vi a necessidade de mudar, de literalmente dar um Reset na vida e aqui achei minha oportunidade! :)

**Comment by 89anderson** [comment]
Oi @fingerfernanda! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
