### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by RamonaDaitx** [cwi-reset/edicao-04-level-1#147]
Olá! Meu nome é Ramona Daitx, trabalhei na área da saúde como auxíliar de enfermagem, agora estou me dedicando para o Reset, estou anciosa para resetar minha carreira!

**Comment by 89anderson** [comment]
Oi @RamonaDaitx! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
