### ISSUE TITLE
Apresentação treinamento CWI

### ISSUE THREAD

**Issue by GabrielVegaRodrigues** [cwi-reset/edicao-04-level-1#148]
Boa tarde pessoal, me chamo Gabriel Vega Rodrigues, tenho 36 anos, cursei Gestão da Tecnologia da informação, porém não cheguei a trabalhar na área. Minha ultima experiência foi na Unimed porto Alegre como Analista de Negócios Pleno ( trabalhava bastante com parametrizações). Mais do que pronto para este novo desafio!!!!

**Comment by 89anderson** [comment]
Oi @GabrielVegaRodrigues! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀

**Comment by GabrielVegaRodrigues** [comment]
> Oi @GabrielVegaRodrigues! Seja bem vinda(o)! A issue que está sendo utillizada para a apresentação é esse link: #1
> 
> Bons estudos🚀

Obrigado!
