### ISSUE TITLE
#Apresentaçao

### ISSUE THREAD

**Issue by FrancieleSNunesMatias** [cwi-reset/edicao-04-level-1#150]
Olá! Me chamo Franciele de Souza Nunes Matias, tenho formação como Técnica de Segurança do Trabalho e Gestão Ambiental. Atualmente atuo de maneira autônoma na área de vendas!

**Comment by 89anderson** [comment]
Oi @FrancieleSNunesMatias ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
