### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by JulianaIsrael** [cwi-reset/edicao-04-level-1#151]
Boa Tarde Pessoal, 
Me chamo Juliana Israel, tenho 37 anos, sou Assistente de RH e estou ansiosa para conhecer esta área da tecnologia!

Boa sorte à todos!!

**Comment by 89anderson** [comment]
Oi @JulianaIsrael ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
