### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by Samara73** [cwi-reset/edicao-04-level-1#152]
Helloooo!!!!
Meu nome é Samara Alicia, tenho 24 anos.
Sou formada em matemática, trabalho como freelancer dando aulas particulares e sou servidora pública municipal. 
Estou muito empolgada com a oportunidade oferecida pela CWI e estou pronta para dar um #Reset na minha carreira.

**Comment by 89anderson** [comment]
Oi @Samara73! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
