### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by brunanunes0596** [cwi-reset/edicao-04-level-1#154]
Olá boa tarde, me chamo Bruna Nunes Chaves. Trabalhei desde pequena no ramo do comércio (Na padaria da minha família), onde aprendi muito. O CWI Reset veio como um recomeço para mim em um ótimo momento. Vamos lá galera, desejo boa sorte á todos!!!

**Comment by 89anderson** [comment]
Oi @brunanunes0596 ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1 

Bons estudos🚀
