### ISSUE TITLE
Edivania Moreira

### ISSUE THREAD

**Issue by eamoreira** [cwi-reset/edicao-04-level-1#155]
Olá pessoal, Me chamo Edivania Moreira!
Sou da área administrativa financeira e estou muito grata por fazer parte do RESET, para poder fazer minha tão esperada transição de carreira.

**Comment by 89anderson** [comment]
Oi @eamoreira! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1 
Bons estudos🚀
