### ISSUE TITLE
[Apresentação] 

### ISSUE THREAD

**Issue by kaanda** [cwi-reset/edicao-04-level-1#160]
Oii pessoal, tudo bem com vocês? Estou muito feliz de estar aqui :) Meu nome é Kaanda Lopes, moro em Porto Alegre/RS e estou querendo mudar de carreira. Hoje trabalho como analista financeira e DPO em uma empresa de consultoria de inovação. Muito obrigada por vocês darem essa oportunidade de mudança de carreira, estou SUPER empolgada!!!

**Comment by joprestes** [comment]
Oi @kaanda ! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

**Comment by kaanda** [comment]
obrigada @joprestes :)
