### ISSUE TITLE
Boa tarde, pessoal!

### ISSUE THREAD

**Issue by marcillio** [cwi-reset/edicao-04-level-1#166]
Me chamo Marcílio, trabalho como tecnico em hardware em uma rede de Atacado. Estou aqui para dar um RESET na carreira em busca de uma melhor qualidade de vida e trabalho.

**Comment by 89anderson** [comment]
Oi @marcillio ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
