### ISSUE TITLE
[Primeira Missão] [Apresentação] Fala, pessoal! Gostaria de me apresentar para vocês!

### ISSUE THREAD

**Issue by caiomfa** [cwi-reset/edicao-04-level-1#167]
Meu nome é Caio Marques, trabalho com marketing há 6 anos e hoje atuo mais na parte do marketing político e eleitoral.

Vai ser um prazer fazer essa imersão proporcionada pela CWI com todos vocês! Desejo um bom Level 1 para todos!

**Comment by Allemaun** [comment]
Buenas @caiomfa 
As apresentações estão sendo feitas na Issue #1

**Comment by caiomfa** [comment]
Opa! Valeu pelo esclarecimento, cara! Achei que era para criar uma issue nova. Valeu mesmo.
