### ISSUE TITLE
Apresentação Deise Leão de Souza

### ISSUE THREAD

**Issue by DeiseLSouza** [cwi-reset/edicao-04-level-1#168]
Boa Tarde Pessoal, 
Me chamo Deise Leão de Souza, 15 anos na área de Recursos Humanos, pronta para dar um reset na carreira, junto com vocês!

**Comment by Allemaun** [comment]
Olá @DeiseLSouza 
As apresentações estão sendo feitas respondendo a Issue #1

**Comment by Cristiano-Fleck** [comment]
Boa noite pessaol!

Me chamo Everson, trabalhei por longos anos trabalhei no ramo metalmecânico e como consultor ERP. E era essa a oportunidade que esperava pra poder resetar minha vida profissional.
