### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by carlamonteiro20** [cwi-reset/edicao-04-level-1#169]
Olá, pessoal! Me chamo Carla, tenho 21 anos e atualmente estou cursando Odontologia, mas quero dar um reset na carreira e me dedicar a área de TI. 
Só vamos!!!

**Comment by 89anderson** [comment]
Oi @carlamonteiro20! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
