### ISSUE TITLE
FriedrichTatiana

### ISSUE THREAD

**Issue by FriedrichTatiana** [cwi-reset/edicao-04-level-1#17]
Boa noite!
Me chamo Tatiana e sou Bacharel em Direito. E agora quero dar um reset na minha carreira.

**Comment by gustavoullmann** [comment]
Oi @FriedrichTatiana! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
