### ISSUE TITLE
Boa noite, pessoal <3

### ISSUE THREAD

**Issue by Saadeh2742** [cwi-reset/edicao-04-level-1#171]
Acabei de ler sobre a _issue_, rsrsrs!
Me chamo Luciano Saádeh, tenho 29 anos, e estou migrando das Ciências biológicas pra T.I.
Agora só vai!****

**Comment by 89anderson** [comment]
Oi @Saadeh2742! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀

**Comment by Saadeh2742** [comment]
Obrigado pelo esclarecimento
