### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by Raianasaadeh** [cwi-reset/edicao-04-level-1#173]
Boa noite!

Meu nome é Raiana, tenho 24 anos. Possuo formação em tecnólogo em Logística e pretendo migrar para área da TI.

**Comment by 89anderson** [comment]
Oi @Raianasaadeh! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
