### ISSUE TITLE
[ Missão 1 - Apresentação]

### ISSUE THREAD

**Issue by RebecaPR** [cwi-reset/edicao-04-level-1#174]
Olá pessoal!

Meu chamo Rebeca Ponciano, e sou advogada. E estou buscando dar um "reset" na minha carreira, estou muito ansiosa em compartilhar conhecimento e experiências com todos vocês! Podem contar comigo no que precisar!

**Comment by 89anderson** [comment]
Oi @RebecaPR! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀

**Comment by RebecaPR** [comment]
Olá @89anderson muito obrigada! 😉
