### ISSUE TITLE
Marcelo Oliveira

### ISSUE THREAD

**Issue by MarceloOliveiraLopes1987** [cwi-reset/edicao-04-level-1#177]
Boa Noite, me chamo Marcelo. Venho da área de Manutenção Automotiva mais especificamente da área de Inspenção Veicular. Busco mudar de área e ter novos desafios profissionais.

**Comment by 89anderson** [comment]
Oi @MarceloOliveiraLopes1987 ! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
