### ISSUE TITLE
duvida - github

### ISSUE THREAD

**Issue by Carolalvws** [cwi-reset/edicao-04-level-1#180]

**Comment by joprestes** [comment]
Olá @Carolalvws , qual seria a sua dúvida?

**Comment by Carolalvws** [comment]
> 

estou me adaptando, entendendo como funciona, obrigada!

**Comment by joprestes** [comment]
Certo, irei fechar esta issue e caso surja alguma dúvida, pode criar outra. No assunto seria interessante utilizar o formato indicado [aqui.](https://github.com/cwi-reset/edicao-04-level-1)
![image](https://user-images.githubusercontent.com/76666518/187315194-93e2dbec-0ccd-44e0-a7f9-27c36196672d.png)
