### ISSUE TITLE
Boa noite pessoal

### ISSUE THREAD

**Issue by Raell899** [cwi-reset/edicao-04-level-1#183]
Sou Rael , sou formado em Gestão da Produção Industrial onde trabalhei 14 anos. e sempre buscando algo novo pra aprender, sou musico também, conserto aparelhos eletrônicos, fiz ums cursos básicos recentemente na dio e um amigos me falo dessa inscrição e to aqui a disposição pra ser um colaborador na  Cwi reset.

**Comment by 89anderson** [comment]
Oi @Raell899! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
