### ISSUE TITLE
[ Sugestão ] Plataforma para facilitar a comunicação 

### ISSUE THREAD

**Issue by weldipaula** [cwi-reset/edicao-04-level-1#184]
Boa noite senhores, gostaria respeitosamente de apresentar uma ideia, afim de agilizar, facilitar e concentrar todas as informações.
Hoje não consegui acompanhar a live, pois não encontrei o link.
Um canal no discord, slack ou telegram, poderia cumprir esse papel. 
agradeço o espaço 👍🏼

**Comment by isaquexavier1155** [comment]
Boa Noite! Estou participando de um grupo que foi criado no Discord
Segue link de acesso: https://discord.gg/3kpwHzym

**Comment by Dklinger5** [comment]
O link para a live estava no mesmo e-mail que lhe trouxe até aqui, é/era só clicar em "acessar live" tem um mouse do lado.

**Comment by weldipaula** [comment]
Este link https://vimeo.com/event/2380359/045316df40, redireciona para um player com a mensagem “este evento ainda não começou”. Já há uma previsão de quando será liberado?

**Comment by diegorafaelvieira** [comment]
Em breve devemos receber um e-mail com o link da gravação.

**Comment by Allemaun** [comment]
Bom dia @weldipaula 

Pelo que entendi nas infos que recebemos, no próximo level terá um servidor no Discord para os que passarem.
Até lá todo o conteúdo oficial está aqui no GitHub e sendo enviado via Email.
Espero estarmos juntos no próximo Level.

**Comment by guilhermewmuller** [comment]
Boa tarde, pessoal!
O link da gravação está disponível aqui no GIT, na lista de calendário das lives.
[https://github.com/cwi-reset/edicao-04-level-1#calend%C3%A1rio-de-lives](url)
