### ISSUE TITLE
Primeira  issue...

### ISSUE THREAD

**Issue by TiagoZorzanello** [cwi-reset/edicao-04-level-1#185]
Boa noite pessoal... Me chamo Tiago Zorzanello, trabalho na área metalúrgica, mas já estou no segundo semestre de análise e desenvolvimento de sistemas. Muito feliz com a oportunidade de adquirir mais conhecimento com o RESET da CWI, espero agarrar com unhas e dentes esta oportunidade de carreira.

**Comment by 89anderson** [comment]
Oi @TiagoZorzanello! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
