### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by DaviNasimento99** [cwi-reset/edicao-04-level-1#187]
Fala galera!! Tudo bem?
Meu nome é Davi. Sou entusiasta no mundo do T.I e vim da área da educação. Tmj!

**Comment by joprestes** [comment]
Oi @DaviNasimento99 ! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
