### ISSUE TITLE
[ Live-abertura-level.1 ERRO 404]

### ISSUE THREAD

**Issue by Adtrn** [cwi-reset/edicao-04-level-1#194]
Oi tudo joinha passando para comunicar em que a live de abertura level.1 esta of-line desde já obrigado

**Comment by ibarbaraluisa** [comment]
Bom dia, saberia informar se a live já esta online novamente?

**Comment by 89anderson** [comment]
bom dia @ibarbaraluisa, a live ocorreu ontem as 19h.

Em breve vocês devem receber, no email que utilizaram para realizar a inscrição no reset, um link onde será possível assistir a gravação da live.

Qualquer dúvida, podes me consultar.

**Comment by isaquexavier1155** [comment]
Ótimo.
