### ISSUE TITLE
Futuro QA

### ISSUE THREAD

**Issue by RonaldoOliver1985** [cwi-reset/edicao-04-level-1#20]
Boa noite,

Sou da cidade de São Paulo, estudo analise e desenvolvimento de sistemas. Comecei a gostar da qualidade de software por conta do meu irmão que já esta na area de testes  há 5 anos, pretendo me especializar e crescer profissionalmente.

**Comment by gustavoullmann** [comment]
Oi @RonaldoOliver1985! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
