### ISSUE TITLE
Apresentação #primeiramissão

### ISSUE THREAD

**Issue by Marina3471** [cwi-reset/edicao-04-level-1#200]
Hello Pessoal!! 
Marina aqui!! Tenho formação na área de computação e atualmente trabalho na área de importação... vamos junto nessa!

**Comment by pedromarreiro12** [comment]
Bom dia, pessoal. Me chamo Pedro e venho da área da comunicação. Estou muito animado pra esse RESET ;)

**Comment by joprestes** [comment]
Oi @Marina3471 e @pedromarreiro12  ! Sejam bem vindos!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
