### ISSUE TITLE
RESET

### ISSUE THREAD

**Issue by TiagoOliveiradaSilva** [cwi-reset/edicao-04-level-1#202]
Olá! meu nome é Tiago, venho da área da vigilância, fico muito grato por esta grande oportunidade, na qual a CWI esta proporcionando com o RESET, boa sorte a todos!

**Comment by TiagoOliveiradaSilva** [comment]
> Olá! meu nome é Tiago, venho da area da vigilância, fico muito grato por esta grande oportunidade, na qual a CWI está proporcionando com o RESET, boa sorte a todos!

**Comment by joprestes** [comment]
Oi @TiagoOliveiradaSilva  ! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
