### ISSUE TITLE
Bora estudar 

### ISSUE THREAD

**Issue by MeCrepaldi** [cwi-reset/edicao-04-level-1#205]
Olá, sou Melissée, atuei por 5 anos na area de RH e estou  dando o reset na carreira, muito obrigada CWI pela oportunidade!! Boraaa 🚀

**Comment by joprestes** [comment]
Oi @MeCrepaldi ! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
