### ISSUE TITLE
AndersonAJO apresentação 

### ISSUE THREAD

**Issue by AndersonAJO** [cwi-reset/edicao-04-level-1#21]
Olá pessoal me chamo Anderson José de Oliveira e venho da área de Gestão da Produção e estou bem animado em dar um #Reset na minha carreira juntamente com todos vocês e o pessoal da CWI 😉!
Abraços!

**Comment by gustavoullmann** [comment]
Oi @AndersonAJO! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
