### ISSUE TITLE
Boa Noite, Galera!

### ISSUE THREAD

**Issue by devalbertomoiseis** [cwi-reset/edicao-04-level-1#212]
Boa Noite, Galera!
Estou feliz, por ser selecionado para fazer da 4° Edição do RESET CWI. 
Acredito que vai ser uma jornada incrível, vamos embarca nesse foguete juntos 😊 
GitHub: https://github.com/devalbertomoiseis
E-mail: contatoalbertomoiseis@gmail.com

**Comment by carolrosa** [comment]
Boa noite @devalbertomoiseis ! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bora se apresentar lá!

**Comment by devalbertomoiseis** [comment]
show, obrigado pela atenção :)

Em ter., 30 de ago. de 2022 às 18:38, CarolRosa ***@***.***>
escreveu:
