### ISSUE TITLE
RESET CWI

### ISSUE THREAD

**Issue by devalbertomoiseis** [cwi-reset/edicao-04-level-1#213]
### Boa Noite, Galera !
Estou feliz em participar da **4 ° Edição do RESET CWI.**
Vai ser uma jornada incrível, vamos pra cima juntos :) 
[GitHub](https://github.com/devalbertomoiseis)
[Portfólio em Construção :) ](https://devalbertomoiseis.netlify.app/)

**Comment by 89anderson** [comment]
Oi @devalbertomoiseis! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
