### ISSUE TITLE
Olá, pessoal! Tudo bem? 

### ISSUE THREAD

**Issue by 01Lu02** [cwi-reset/edicao-04-level-1#215]
Me chamo Luíza atuo na área de Logística e estou muito feliz em me permitir uma mudança de carreira para minha área dos sonhos! Boa sorte a todos nessa nova etapa e bons estudos. 👩‍💻

**Comment by 89anderson** [comment]
Oi @01Lu02! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
