### ISSUE TITLE
Jessika Gama

### ISSUE THREAD

**Issue by Jessikagama31** [cwi-reset/edicao-04-level-1#219]
Boa noiteeee! Venho da área de vendas, mas sou completamente apaixonada por TI.
Muito feliz pela oportunidade de poder dar um reset na minha carreira!
Vamos que vamos!

**Comment by 89anderson** [comment]
Oi @Jessikagama31! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1

Bons estudos🚀
