### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by AlexandreNoguez** [cwi-reset/edicao-04-level-1#22]
Olá, tudo bem? 

Me chamo Alexandre Noguez e estou vindo da área da música!

Agradeço demais a oportunidade de aprender, colaborar e compartilhar conhecimento desta nova área que estou mergulhando de cabeça!

Bons estudos a todos.

**Comment by gustavoullmann** [comment]
Oi @AlexandreNoguez! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
