### ISSUE TITLE
[Duvida] Dificuldade com o GitHub

### ISSUE THREAD

**Issue by Allemaun** [cwi-reset/edicao-04-level-1#225]
Buenas gurizada

Criei meu repositório no GitHub, pasta na minha máquina e clonei o repositório nela, mas não estou conseguindo adicionar um arquivo.

![image](https://user-images.githubusercontent.com/103670434/187663007-77751353-5d23-4d70-9fe6-5ac4ac8b2ee5.png)

**Comment by isaquexavier1155** [comment]
Bom dia. Você tem que executar primeiro o comando git init pra para gerar a pasta Git dentro de sua pasta raíz. Tenta aí. Qualquer coisa estou a disposição para ajudar

**Comment by isaquexavier1155** [comment]
Depois vc executa os outros comandos.(git add .
git commit
git push etc)

**Comment by Allemaun** [comment]
Até usei esse comando mas aí deu outro erro
![image](https://user-images.githubusercontent.com/103670434/187667623-274bcef2-f531-4336-9eca-cdec9ca967ef.png)

**Comment by isaquexavier1155** [comment]
Tenta remover a pasta git que foi gerada na sua pasta raiz e refaz todo o processo novamente

**Comment by Allemaun** [comment]
Farei isso

**Comment by arielcBR** [comment]
> Até usei esse comando mas aí deu outro erro ![image](https://user-images.githubusercontent.com/103670434/187667623-274bcef2-f531-4336-9eca-cdec9ca967ef.png)

Bom dia.

Sempre ao iniciar o GIT deve ser inicializado com o comando **git init**
Após a inicialização tu pode digitar **git status**, ao pressionar enter o git irá te mostrar no terminal se há algum arquivo novo/modificado ou arquivos deletados.
Caso queira criar um novo ponto tu tem que escrever **git add .** dessa forma o git irá adicionar todos os arquivos no diretório que ele está trabalhando.
Depois tu escreve **git commit -m "mensagem explicando o que foi alterado"**
Para verificar tua criação pode escrever **git log**, ai tera que exibir teu commit criado com o log e hash.

Tenta ai, se não conseguir responde na issue.

**Comment by Allemaun** [comment]
Farei isso mais tarde @arielcBR 
Grato por hora

**Comment by Allemaun** [comment]
Buenas gurizada

Aos que me ajudaram, muito obrigado.
Descobri que era um comando que deixei passar.
git cd só isso mesmo.
