### ISSUE TITLE
[TESTE-FASE=1]+[DISCIPLINA-FUNDAMENTOS-FERRAMENTAS]

### ISSUE THREAD

**Issue by Adtrn** [cwi-reset/edicao-04-level-1#228]
Ola tudo joinha..?  bem vamos lá a duvida que gostaria de ser sanada como o título se refere o TESTE-FASE1, será múltipla escolha baseada em fundamentos ok .mas será  apenas na teoria fundamentalista ou em duplo sentido fundamentalista e aplicação de problemas dentro de ferramentas. minha maior duvida é terei de saber ferramentas para solucionar a FASE1 OBS: esse contexto todo descrito dentro de fundamentos não aplicavel a LÓGICA DE PROGRAMAÇÃO

**Comment by isaquexavier1155** [comment]
Boa tarde! Na minha opinião a prova do nível 1 terá algumas questões alternativas sem uso de qualquer ferramenta de teste. E três questões práticas que poderão ser resolvidas com o uso de alguma ferramenta específica.

**Comment by Allemaun** [comment]
Boa tarde @Adtrn 

 Embora não possamos afirmar, nem tampouco nos acomodar nos estudos, mas podemos levar em consideração a matéria que nos foi proposta.
 Inicialmente a matéria não exige uso de ferramenta alguma, mas nos últimos módulos sim.
 Então acredito que sim, teremos de resolver algum teste real e prático.
 E se não, ao menos precisaremos estar prontos pra isso.

**Comment by 89anderson** [comment]
Boa tarde pessoal, todos bem?

Respondendo ao @Adtrn, a prova final do level 1 será sobre todo o conteúdo que foi abordado durante as aulas enunciadas durante o level 1. Isso pode incluir as ferramentas que foram citadas durante esse treinamento.

É importante ressaltar, porém, que todo o conteúdo da prova está diretamente linkado com este material. Não será cobrado nada que não tenha sido apresentado para vocês.
