### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by LarissaThewes** [cwi-reset/edicao-04-level-1#229]
Olá, colegas Reset e time CWI!

Me chamo Larissa Thewes, tenho 29 anos, sou de Novo Hamburgo/RS e através da graduação em Tecnologia da Informação estou retornando ao mercado de trabalho após alguns anos ausente. Minha última experiência foi como corretora de imóveis em 2018. Sendo assim, momento reset na carreira.

Meus votos de sucesso a todos em suas trajetórias profissionais e desde já grata pela oportunidade. Em frente! 🚀

**Comment by 89anderson** [comment]
Oi @LarissaThewes! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1
