### ISSUE TITLE
[Módulo 2 - Níveis de teste - Aula 02 - Pirâmide de Teste]

### ISSUE THREAD

**Issue by nairacirino** [cwi-reset/edicao-04-level-1#230]
Boa tarde, pessoal! Só pra avisar que o link do vídeo desta aula ficou com algum erro, talvez de digitação. Mas funciona normalmente ; )

**Comment by 89anderson** [comment]
Boa tarde @nairacirino tudo bem?
Obrigado pela observação. Já comuniquei o pessoal. 😃
