### ISSUE TITLE
Ainda não recebi o link da aula inaugural 

### ISSUE THREAD

**Issue by joaofmds** [cwi-reset/edicao-04-level-1#231]
Boa tarde, infelizmente não consegui assistir a aula ao vivo, fui informado que seria enviado um link da aula via e-mail, porém, ainda não recebi.
Poderiam me ajudar, por gentileza?

**Comment by guilhermewmuller** [comment]
Boa tarde @joaofmds, tudo certo?
Os e-mails foram disparados e devem estar chegando no teu e-mail.
Até lá, você pode ter acesso aos links através do calendário de lives aqui do GIT.
https://us06web.zoom.us/j/81823207794?pwd=U2Mya09YU05EUlpZY3JnYXRONGRUZz09
