### ISSUE TITLE
Primeira Issue

### ISSUE THREAD

**Issue by brunodutra2210** [cwi-reset/edicao-04-level-1#232]
Boa tarde pessoal! Me chamo Bruno Dutra e estou super empolgado para dar um reset na carreira, atuei como Suporte Técnico por 1 ano. Let's Code!

**Comment by Fabianakirsch** [comment]
Boa tarde @brunodutra2210! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: #1 

Bons estudos🚀

**Comment by Fabianakirsch** [comment]
Oi @brunodutra2210! Seja bem vindo :)
A issue que está sendo utillizada para a apresentação é esse link: #1 

Bons estudos🚀

**Comment by brunodutra2210** [comment]
Obrigado Fabiana! Agora percebi que criei no local errado 🤦🏻‍♂️
