### ISSUE TITLE
Complemento ao tema nivel de testes

### ISSUE THREAD

**Issue by Allemaun** [cwi-reset/edicao-04-level-1#235]
Buenas gurizada

Ao estudar sobre testes caixa preta e testes caixas branca, embora estivesse entendendo não estava muito claro o conceito.
Fiz uma breve pesquisa e encontrei uma explicação que não deixou espaço pra dúvidas e quero muito compartilhar com vocês, para o caso de mais alguém estar precisando algo a mais.
Segue link abaixo:
https://blog.geekhunter.com.br/tecnicas-de-caixa-preta-e-branca-para-teste-de-software/

Bora pra cima!

**Comment by rosenirmaria13** [comment]
> Buenas gurizada
> 
> Ao estudar sobre testes caixa preta e testes caixas branca, embora estivesse entendendo não estava muito claro o conceito.
> Fiz uma breve pesquisa e encontrei uma explicação que não deixou espaço pra dúvidas e quero muito compartilhar com vocês, para o caso de mais alguém estar precisando algo a mais.
> Segue link abaixo:
> https://blog.geekhunter.com.br/tecnicas-de-caixa-preta-e-branca-para-teste-de-software/
> 
> Bora pra cima!

Obrigada por compartilhar o material. Vou dá uma olhada!

**Comment by MeCrepaldi** [comment]
> Buenas gurizada
> 
> Ao estudar sobre testes caixa preta e testes caixas branca, embora estivesse entendendo não estava muito claro o conceito. Fiz uma breve pesquisa e encontrei uma explicação que não deixou espaço pra dúvidas e quero muito compartilhar com vocês, para o caso de mais alguém estar precisando algo a mais. Segue link abaixo: https://blog.geekhunter.com.br/tecnicas-de-caixa-preta-e-branca-para-teste-de-software/
> 
> Bora pra cima!

Isso me ajudou muuito, obrigada!

**Comment by CamilaGoulart** [comment]
muito obrigada por compartilhar.

**Comment by Allemaun** [comment]
> > Buenas gurizada
> > Ao estudar sobre caixas brancas e testes de caixa preta, embora realmente entendendo não está muito claro o conceito. 
> > Fiz uma breve pesquisa e encontrei uma explicação que não deixou espaço pra dúvidas e quero muito compartilhar com o caso de mais alguém precisando algo a mais. 
> > Segue link abaixo: 
> > https://blog.geekhunter.com.br/tecnicas-de-caixa-preta-e-branca-para-teste-de-software/
> > Bora pra cima!
> 
> Obrigada por compartilhar o material. Vou dar u

**Comment by Allemaun** [comment]
Que bom conseguir ajudar de alguma forma pessoal

**Comment by mayclau** [comment]
Obrigado, ajuda muito a estudar!
