### ISSUE TITLE
Primeira Missão!

### ISSUE THREAD

**Issue by CamilaCarvalhoCezar** [cwi-reset/edicao-04-level-1#236]
Opa Pessoal! Tudo na paz?

Me chamo, Camila Carvalho e sou formada em Comunicação Social com linha de formação em Educomunicação.  Vi na CWI uma grande oportunidade de dar um #UP na minha vida fazendo esse reset na minha carreira profissional. Estou muito animada.

PraCimaTime^

**Comment by Allemaun** [comment]
Buenas @CamilaCarvalhoCezar 

As apresentações estão sendo feitas na #1 
Tem uma galera lá esperando pra te conhecer.

**Comment by juniork09** [comment]
Oi galera! Me chamo Antonio Lourenço, sou técnico em mecânica industrial, trabalhando atualmente na área. Já venho a um tempo pensando em mudar de área, pesquisando muito para ver em qual me encaixo melhor e nessa pesquisa me deparei com CWI e essa oportunidade de mudança, estou gostando desse primeiro contato com a área, vou levar adiante e me capacitar cada vez mais e espero passar para segunda fase e me encontrar com vocês por la.

**Comment by Tatianaftkj38** [comment]
Olá Galera!
Me chamo Tatiana, tenho 44anos e sou de Sapucaia do Sul no RS. Trabalhei durante nove anos com Educação Infantil e estou fora do mercado de trabalho a 6 anos. Quero muito retornar ao mercado de trabalho e vi no RESET uma oportunidade de retorno e até mesmo um desafio. Agradeço muito a CWI por essa oportunidade.  E tenham certeza que farei o meu melhor. Obrigada e abraços a todos.

**Comment by nathirchavez01** [comment]
Olá pessoal! 

Me chamo Nathália, tenho 21 anos. Estou dando um Reset na minha carreira de "mãe em tempo integral" e entrando para o mundo da tecnologia da informação. Fui mãe aos 18 anos e me abdiquei de escolher qual área seguir para zelar o primeiro aninho de vida da minha bebê, enfim terminei o ensino médio com um bebê recém nascido e não tive tempo de pensar qual carreira seguir.

Habilidades: trocar fraldas, fazer mamadeira, dormi com a neném no colo, tomar banho em 5 minutos. (Brincadeiras a parte rsrs)

Tenho certeza que daqui alguns meses depois da oportunidade que a CWI está me dando, eu tenha literalmente dado um RESET nessas "Habilidades" . Eu tenho o enorme prazer de fazer parte desse projeto, e adquirir todo tipo de conhecimento que a CWI.reset tem a me oferecer.

Ultima experiência profissional, trabalhei cerca de 1 ano em um studio de beleza/estética como designer de sobrancelhas, e lash designer.

**Comment by carolrosa** [comment]
Bom dia pessoal @juniork09 @nathirchavez01! Seja bem vindos!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
