### ISSUE TITLE
Ola galera do #resetcwi

### ISSUE THREAD

**Issue by Crisdeuner** [cwi-reset/edicao-04-level-1#24]
Meu nome é Cristiane Deuner. Sou formada na área do agro, mas atualmente trabalho com artesanato e costura no atelie da minha mãe.
Estou super feliz e empolgada por dar um #reset na minha carreira.  Muito obrigada CWI pela oportunidade 🚀❤

**Comment by gustavoullmann** [comment]
Oi @Crisdeuner! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
