### ISSUE TITLE
Missão 01 programa reset

### ISSUE THREAD

**Issue by Nightwertyu** [cwi-reset/edicao-04-level-1#240]
Olá bom dia. Me chamo Washington Luiz Freitas da Silva, estou ansioso para iniciar as tarefa. Desde de que conheci os computadores me apaixonava casa dia mais a cada descoberta de funções e etc. Venho da área da Saúde e sempre sonhei desde adolescente em trabalhar na área de TI.
Desde já muito obrigado a todos pela oportunidade.

**Comment by carolrosa** [comment]
Bom dia @Nightwertyu! Seja bem vinda(o)!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
