### ISSUE TITLE
Primeira missão! #1 

### ISSUE THREAD

**Issue by Andrielevict** [cwi-reset/edicao-04-level-1#241]

**Comment by joprestes** [comment]
Bom dia @Andrielevict ! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀

**Comment by Paulohack** [comment]
Sejam todos bem vindos, tamo junto!
