### ISSUE TITLE
 PRIMEIRA MISSSÃO

### ISSUE THREAD

**Issue by Robertofabianorodrigues** [cwi-reset/edicao-04-level-1#243]
Boa tarde pessoal!! eu me chamo Roberto Fabiano e tenho 48 anos atuo na área de produção industrial a mais de 20 anos ,estou muito contente pela oportunidade de estar participando do Reset /  edição 4 , bora resetar boa sorte a todos !!!

**Comment by carolrosa** [comment]
Olá @Robertofabianorodrigues! Seja bem vindo(a)!
A issue que está sendo utillizada para a apresentação é esse link aqui: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
