### ISSUE TITLE
Primeira missão :)

### ISSUE THREAD

**Issue by AndrezaCustodio** [cwi-reset/edicao-04-level-1#246]
Olá pessoal, sou a Andreza e tenho 25 anos. Estou em transição de carreira, de contabilidade para TI. Fiz um bootcamp de backend .net na linguagem c# e lá fui exposta nesse mundo de qualidade e me apaixonei. E agora estou estudando e buscando cada vez mais ficar imersa nesse mundo! E estou muito feliz de estar começando esse programa incrível com a CWI.

**Comment by joprestes** [comment]
Bom dia @AndrezaCustodio ! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
