### ISSUE TITLE
Deivid Bomfim

### ISSUE THREAD

**Issue by DeividBomfim** [cwi-reset/edicao-04-level-1#248]
Olá, boa noite/dia! 
Me chamo Deivid Bomfim, moro em Salvador-Bahia, tenho 18 anos.
Será um prazer participar dessa edição da CWI, tenho certeza que irei adquirir muitos conhecimentos com vocês.

**Comment by joprestes** [comment]
Bom dia @DeividBomfim  ! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
