### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by lpmaa** [cwi-reset/edicao-04-level-1#25]
Olá me chamo Luiz Paulo Monteiro de Almeida Alves, estou em busca de minha migração de carreira pois já fui muitas coisas na vida e quero criar raízes fortes na área de Qualidade de Software. Sou formado em Geografia e atualmente curso Analise e Desenvolvimento de Sistemas. 
Estou super feliz e animado por dar um #reset na minha carreira. Muito obrigada CWI pela oportunidade 🚀

**Comment by gustavoullmann** [comment]
Oi @lpmaa! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
