### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by nayaracastro** [cwi-reset/edicao-04-level-1#250]
Ola pessoal !
Me chamo Nayara, sou suporte tecnico há 5 anos e este ano me dediquei a area de Qualidade de Software. É um prazer esta fazendo esse curso com voces  = )

**Comment by 89anderson** [comment]
Bom dia @nayaracastro   ! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: #1 

Bons estudos🚀
