### ISSUE TITLE
 [Aula 08] [Estruturas de repetição] [exercício 3] meu código imprime todos os 60 nomes do array

### ISSUE THREAD

**Issue by superjhonatan** [cwi-reset/edicao-04-level-1#253]
<h3>Meu código imprime 60 mensagens</h3> 

``` 
let nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia",
  "Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia",
  "Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina",
  "Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia",
  "Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda",
  "Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]


for (i = 0; i < nomesComuns.length; i++) {
let meuNome = "Leonardo";
  
if(meuNome === nomesComuns[i]){
    console.log("É, nome comum :P.")
  }
  else{
    console.log("Diferentão, hein? XD.")
  }
}

**Comment by arielcBR** [comment]
Oi.

O código está certo, teu array nomeComuns tem 60 elementos.

Se você quiser parar a impressão no console após encontrar o conteúdo da variável meuNome, tu deveria adicionar dentro do o comando **break**, desta forma interromper o loop for.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/break

´´´´
let nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia",
  "Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia",
  "Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina",
  "Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia",
  "Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda",
  "Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]

let meuNome = "Leonardo";
for (i = 0; i < nomesComuns.length; i++) {
  
if(meuNome === nomesComuns[i]){
    console.log("É, nome comum :P.")
    break
  }
  else{
    console.log("Diferentão, hein? XD.")
  }
} 
´´´

**Comment by superjhonatan** [comment]
@arielcBR na verdade eu quero que seja impresso apenas uma das duas mensagens do código apenas uma vez.

tentei da forma que você indicou porém continua imprimindo mais de uma mensagem.

imagino que eu tenho que rodar o loop para verificar se o valor da variavel meuNome existe dentro do array nomesComuns e fazer a impressão fora do loop

**Comment by arielcBR** [comment]
> @arielcBR na verdade eu quero que seja impresso apenas uma das duas mensagens do código apenas uma vez.
> 
> tentei da forma que você indicou porém continua imprimindo mais de uma mensagem.
> 
> imagino que eu tenho que rodar o loop para verificar se o valor da variavel meuNome existe dentro do array nomesComuns e fazer a impressão fora do loop mas não estou conseguindo chegar no raciocínio correto para fazer dessa forma.

Dessa forma imprime somente uma vez.

```javascript

let nomesComuns = ["Miguel", "Laura", "Lucas", "Beatriz", "Guilherme", "Maria", "Gabriel", "Ana", "Arthur", "Júlia",
  "Enzo", "Alice", "Rafael", "Mariana", "João", "Larissa", "Gustavo", "Maria Eduarda", "Pedro", "Sofia",
  "Bernardo", "Isabela", "Matheus", "Helena", "Davi", "Camila", "Heitor", "Lara", "Henrique", "Valentina",
  "Bruno", "Letícia", "Samuel", "Luana", "Felipe", "Amanda", "Lorenzo", "Yasmin", "Benjamin", "Sophia",
  "Vinícius", "Rebeca", "Rodrigo", "Juliana", "Eduardo", "Bruna", "Diego", "Cecília", "Antônio", "Fernanda",
  "Leonardo", "Isadora", "Noah", "Lorena", "Nícolas", "Lívia", "Daniel", "Manuela", "Thiago", "Vitória"]

let meuNome = "Leonardo";

const verificaNome = (meuNome) => {
  for (let i = 0; i < nomesComuns.length; i++) {
    if (meuNome === nomesComuns[i]) return true
  } 
}

  if(verificaNome(meuNome) === true) console.log("É, nome comum :P.")
  else console.log("Diferentão, hein? XD.")
```

**Comment by superjhonatan** [comment]
obrigado @arielcBR

**Comment by williamirassochio** [comment]
nome = input("Digite seu nome ")

for nomes in nomesComuns:
    if nome in nomesComuns:
        print("Uhuu, {} está na lista.".format(nome))
        break
    else:
        print("{} é diferentão heim?! Este nome não está na lista".format(nome))
        break

Boa noite pessoal!
Estou com uma certa dificuldade nas linguagens.
Estou com nível básico em Python como fiz neste exercício e surgiu a dúvida se posso fazer as atividades com o que venho estudando ( Python)? 
Não sei se seria uma boa misturar o aprendizado de uma primeira linguagem neste meu momento.
O que vocês podem me dizer nesta situação?
