### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by Pheliquiz** [cwi-reset/edicao-04-level-1#255]
Olá pessoal! Me chamo Félix estou com 17 anos e trabalho no Grupo Caio. Estou ansioso para dar meus primeiros passos na tecnologia!😆l

**Comment by joprestes** [comment]
Bom dia @Pheliquiz ! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
