### ISSUE TITLE
Meu primeiro Issue

### ISSUE THREAD

**Issue by GENEHON** [cwi-reset/edicao-04-level-1#256]
Boa noite, pessoal. Estou muito feliz pela oportunidade, sou feirante, e vou dar um RESET total na minha carreira. Vamos com tudo e bons estudos a todos! 

 Nos vemos na próxima etapa.

**Comment by joprestes** [comment]
Bom dia @GENEHON ! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos🚀
