### ISSUE TITLE
Pagina Material [Aula 02] - (Pirâmide de Teste)

### ISSUE THREAD

**Issue by paulohenriquesa** [cwi-reset/edicao-04-level-1#259]
Boa tarde, só pra exercitar:
Não sei se foi um erro proposital, mas observando a pagina da aula 02 - Pirâmide de Testes, vi que a formatação de apresentação do link está diferente das outras paginas, nesta não há tag href para a vídeo aula.
https://cwi-reset.github.io/edicao-04-level-1/02-niveis-e-casos-de-teste/aula02/aula.html

Então fiz uma comparação com as demais paginas, e ajustei para que fosse apresentado em formato de hiper link.
Trecho original
```html
<tr>
          <td>[Pirâmide de Testes</td>
          <td>O que é e pra que serve?](https://youtu.be/hizne8Yc_Dg)</td>
        </tr>
```
Ajuste
```html
<tr>
          <td>Pirâmide de Testes</td>
          <td><a href="https://youtu.be/hizne8Yc_Dg">O que é e pra que serve?
          </a></td>
        </tr>
```

**Comment by guilhermewmuller** [comment]
Oi, Paulo :)
Dei uma conferida aqui e parece estar tudo OK com os links. São 2 formas diferentes de linkar URLs aqui no GIT. Ambas funcionam.

**Comment by paulohenriquesa** [comment]
Boa tarde Guilherme, aqui pra mim aparece assim:
![image](https://user-images.githubusercontent.com/17592551/188496383-c3a6dbce-5027-4f40-9425-a3a457211581.png)

**Comment by paulohenriquesa** [comment]
Obs.; Testei no Chrome, Edge, Firefox, Opera, Brave...
![image](https://user-images.githubusercontent.com/17592551/188499588-d51be996-24cb-46fd-9a4d-e51fdf939b3f.png)

**Comment by paulohenriquesa** [comment]
Obs.; Testei no Chrome, Edge, Firefox, Opera, Brave, Tor...
![image](https://user-images.githubusercontent.com/17592551/188499753-161077f9-d9f9-485f-97a9-bc7fe71bf455.png)

**Comment by guilhermewmuller** [comment]
Oi @paulohenriquesa 
Aqui para mim está tudo dentro do esperado (na minha máquina funciona kkk)
![image](https://user-images.githubusercontent.com/68305119/188500088-33f24834-96d3-4d3e-8397-9adf5d8d882f.png)

Fiz uma pequena modificação lá na página. Dá uma olhada se surtiu algum efeito na visualização ai para ti. Me avisa qualquer coisa.

**Comment by paulohenriquesa** [comment]
Oi @guilhermewmuller, algo erro não está certo kkk
Tentei no Ubuntu (dualboot), e também em uma VM, e nada, continua não aparecendo do hiperlink.
![image](https://user-images.githubusercontent.com/17592551/188506810-9d53c56b-2629-4dcd-b6f7-e298bbce7b5d.png)

**Comment by paulohenriquesa** [comment]
Oi @guilhermewmuller, onde posso ver um exemplo explicando essa sintaxe HTML com "tb" [ ] ( ) para hiper link?

Obs.: No meu smartphone não aparece também.

![Screenshot_20220905-170507.png](https://user-images.githubusercontent.com/17592551/188508098-8a3ea264-f6f8-4dc4-b950-8fd34e6be072.png)

**Comment by guilhermewmuller** [comment]
Oi @paulohenriquesa 
Estamos verificando o que pode estar ocorrendo.

Como não é algo impeditivo para os estudos e não é para todos que ocorre, sugiro que dê continuidade e assim que tivermos alguma novidade, comento aqui. 🚀

**Comment by ernestosbarbosa** [comment]
Oi pessoal
O problema ocorreu devido ao caracter `|`. No markdown ele é um tabulador de colunas em tabelas. Por algum motivo desconhecido por nós o GitHub Flavored Markdown (processador de markdown usado nas Pages do Github) interpretou esse pipe que está no meio do texto como um separador. Alteramos no material e agora está tudo ok 😊
🚀
