### ISSUE TITLE
Apresentação - Laura Loss

### ISSUE THREAD

**Issue by LauraLoss** [cwi-reset/edicao-04-level-1#26]
Boa noite, pessoal! 
Me chamo Laura Loss, tenho 19 anos. Venho da área de automação industrial. :)

**Comment by gustavoullmann** [comment]
Oi @LauraLoss! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
