### ISSUE TITLE
Formulario da LIVE

### ISSUE THREAD

**Issue by derodrig0** [cwi-reset/edicao-04-level-1#263]
Alguém poderia passar o link, para eu poder responder, não consegui clicar a tempo antes do fechamento da live

 att,

Rodrigo Alves da Rosa.

**Comment by BrunaTFerreira** [comment]
Na primeira live só consegui responder quando recebi o e-mail da live gravada uns dias depois.

**Comment by Allemaun** [comment]
Boa noite @derodrig0 

Eu respondi hj o formulário da live1, recebi no E-mail ele.

**Comment by derodrig0** [comment]
> [https://docs.google.com/forms/d/e/1FAIpQLSdN3ZzUKmKvtDr2tfPZWV7ByrfygEtPQ-bEMksLU7bBjLQmtA/viewform](url)

muito obrigado @j-crc  !

**Comment by PauloViniciusBirck** [comment]
Boa noite, pessoal , não recebi nenhum link nem da 1ª live nem da 2ª  por e-mail e este link que esta acima não esta direcionando para lugar nenhum , o que fazer?

**Comment by Allemaun** [comment]
Boa noite @PauloViniciusBirck

No README do repositório abaixo do cronograma tem a programação das lives com seus devidos links .
Mas após as lives saírem do ar o Vimeo gera outro link, só aguardar atualizar e rever elas.

**Comment by 89anderson** [comment]
Olá @PauloViniciusBirck, bom dia! Tudo bem?
Todo o conteúdo do level 1, seja referente aos estudos ou as lives, voce encontra nesse link:
https://github.com/cwi-reset/edicao-04-level-1

Sobre os emails, verifique se não está caindo no spam. Todos os contatos oficiais são feitos através do e-mail que você utilizou para a sua inscrição!

Qualquer dúvida, podes me procurar ou abrir uma issue 😃

**Comment by JuliaKLS** [comment]
Boa tarde, também não recebi o link por e-mail nem consegui pegar o link na hora da live, passou muito rápido! Já verifiquei meu spam e não tem e-mail lá, assim também como no material do GIT só aparece o link da live, não encontro o do formulário. E nesse link que os colegas disponibilizaram não tem nada.

**Comment by JuliaKLS** [comment]
Agora deu certo, obrigada @j-crc!
