### ISSUE TITLE
Olá time CWI

### ISSUE THREAD

**Issue by Caestevao** [cwi-reset/edicao-04-level-1#265]
Meu nome é Carla Aparecida Gomes Alves Estevão, estou atuando há 1 ano em testes funcionais, estou em busca de novos conhecimentos com o objetivo de me aprofundar e adquirir sólidos conhecimentos em testes automatizados.

**Comment by joprestes** [comment]
Olá @Caestevao! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link aqui: #1

Bons estudos🚀
