### ISSUE TITLE
Prova Level 1

### ISSUE THREAD

**Issue by tikaoo** [cwi-reset/edicao-04-level-1#267]
Olá boa tarde, tudo bem??? minha duvida é referente a prova level 1.

Ela será de múltipla escolha? e  quantas questões?

Qual a nota de corte?

obrigado

**Comment by superjhonatan** [comment]
@tikaoo, se não me falha a memoria, na primeira live foi dito que vai ter  teórica e  prática. 

Sobre ser de múltipla escolha: Imagino que a parte teórica será de múltipla  escolha porque a parte prática é equivalente a uma prova escrita.

Quanto a quantidade de questões: não foi divulgada ainda, geralmente nenhum processo seletivo passa essa informação.

Sobre a nota de corte: por ser um processo seletivo diferenciado, focado em quem nunca atuou na área antes, e ter muuitos candidatos essa nota de corte não foi definida. Imagino que os critérios de avaliação serão bem além da nota que for tirada na prova. Na ultima live tivemos a presença de Carol, uma das contratadas no Reset Passado. Perguntaram várias coisas a ela e dentre as perguntas que fizemos a ela destaco duas aqui:


**Pergunta: Carol, como foi a prova do final do level 1?
Resposta: não se preocupem com a prova, se preocupem em estudar o conteúdo e aprender, a prova é a parte facil.

Pergunta: Carol, antes do reset você já tinha conhecimento na área de TI?
Resposta: Eu fiz um curso de técnico de informática a muito tempo atrás, não lembrava mais de quase nada do curso, basicamente aprendi tudo no programa reset.**

claro que essas não foram exatamente as mesmas palavras e provavelmente eu errei uma coisa aqui outra ali sobre a parte da carol mas é basicamente isso.
