### ISSUE TITLE
Boraa reset

### ISSUE THREAD

**Issue by Evarosa** [cwi-reset/edicao-04-level-1#27]
Olá, boa noite. Me chamo Eva Caroline, trabalho atualmente com digitalização e cópias de processo e assistente financeiro, formada em técnico em Contabilidade e pronta pra dar um reset na minha vida 💪🏿🙅🏿‍♀️💜

**Comment by gustavoullmann** [comment]
Oi @Evarosa! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
