### ISSUE TITLE
link da live do dia 5

### ISSUE THREAD

**Issue by antoniapires** [cwi-reset/edicao-04-level-1#270]
Não pude assistir a live do dia 5, onde encontro ou como tenho acesso à ela?

**Comment by 89anderson** [comment]
Bom dia @antoniapires tudo bem?

Todos os links estão concentrados nessa página: [https://github.com/cwi-reset/edicao-04-level-1](aqui.)

A gravação da live do dia 5 tu encontra [https://vimeo.com/744736042/4cdf0d0ce0](aqui.)
