### ISSUE TITLE
Aula 9 [Lógica de programação] [EXRCÍCIO MÉDIA ARITIMETICA]

### ISSUE THREAD

**Issue by superjhonatan** [cwi-reset/edicao-04-level-1#272]
Pessoal, boa tarde. Eu estou tão perdido que não estou nem conseguindo explicar direito mas valor la.

um dos exercícios da aula 9 é:  Na função da média aritmética, evite colocar todos os itens como argumentos do método, pois isso limitaria sua utilização a um número fixo de elementos. Tente implementar uma lógica para receber um array e calcular a média em cima dele, tornando a função mais reaproveitável em diferentes situações.

desde o sábado passado que eu tento resolver esse exercício e hoje cheguei em algum resultado, porém não entendi bem em que resultado. Fui na tentativa e erro (aprendi até a limitar uma dizima periódica) mas não sei se o resultado em que cheguei é o resultado esperando e não entendi completamente a lógica dele.

vou deixar meu código abaixo e gostaria que as pessoas que entenderam e resolveram a questão corretamente me desse um feedback sobre o meu código e sobre a questão em si porque muito provavelmente eu fiz errado.

```
function imprimir(item) {
    console.log(item)
};

function MediaAritimetica(itens) {
    let soma = 0;

    for (let i= 0; i < itens.length; i++) {
        soma = itens[i] + soma;
    }
    return soma / itens.length;
}

let resultado = MediaAritimetica([1,8,5,3,4,2,10,20,35]);
imprimir(resultado.toFixed(2));

**Comment by cristianodc** [comment]
É tranquilo a variável **soma** em cada iteração do array  vai incrementando seu resultado com o valor de cada posiçao do array assim:
**soma** = itens[posicao] + soma "Lembrando que na primeira iteração a varialvel **soma** vale zero."
**soma** = 1 + 0; depois começa 
ate que a vairavel receba todas os valores do array somados
depois esse valor  é divido pelo tamanho total do array 
**soma / itens.length;**  fica assim 
**soma/9** 
é uma media aritimetica ;
espero ter ajudado

**Comment by superjhonatan** [comment]
ajudou sim @cristianodc, obrigado.
