### ISSUE TITLE
Live

### ISSUE THREAD

**Issue by rafacarneiro86** [cwi-reset/edicao-04-level-1#279]
Alguém está conseguindo acessar a live de hj 09/09

**Comment by rosenirmaria13** [comment]
Consegui acessar sim. Os links das live's ficam aqui https://github.com/cwi-reset/edicao-04-level-1 
E também foram enviados todos os links por email. Mas ficou gravada e você pode assistir a gravação que também vai ficar nesse endereço acima. 
Bons estudos!
