### ISSUE TITLE
Reset go....

### ISSUE THREAD

**Issue by danbunny22** [cwi-reset/edicao-04-level-1#28]
Olá, me chamo Daniel sou da área de logística a mais de 7 anos tenho um filho de 2 meses .
Vou dar um Reset na minha carreira e estou preparado para os desafios.
Vamooooo

**Comment by gustavoullmann** [comment]
Oi @danbunny22! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
