### ISSUE TITLE
[Formulário Avaliação Live 09/09]

### ISSUE THREAD

**Issue by rosenirmaria13** [cwi-reset/edicao-04-level-1#280]
Não consegui responder o formulário de avaliação da live. Se alguém pegou o link, poderia colocar aqui?

**Comment by pedroanguinonni** [comment]
Bom dia! O link do formuário é sempre enviado, por e-mail, um dia após a transmissão da mesma. Ainda hoje, deverá receber o e-mail ;)

**Comment by rosenirmaria13** [comment]
> Bom dia! O link do formuário é sempre enviado, por e-mail, um dia após a transmissão da mesma. Ainda hoje, deverá receber o e-mail ;)

Obrigada, acabei de receber 🙂

**Comment by Alinervit** [comment]
Eu também não recebi o link ainda :(

**Comment by igoroliveirasilva** [comment]
[Feedback Live](https://forms.gle/154yuwaBFqZV3k1i9)

**Comment by joprestes** [comment]
Boa noite Pessoal!
 @rosenirmaria13 e @Alinervit  conseguiram responder o form de Feedback?

**Comment by rosenirmaria13** [comment]
>  Boa noite Pessoal!
>  @rosenirmaria13 e @Alinervit  conseguiram responder o form de Feedback?

Sim, consegui. Recebi por email o formulário.

**Comment by Alinervit** [comment]
@rosenirmaria13  e @joprestes Consegui sim responder,recebi no e-mail. Obrigada pela atenção ☺️

**Comment by joprestes** [comment]
Certo, vou fechar essa issue então.

Ficamos à disposição.

Reset, restart, go! 🚀
