### ISSUE TITLE
bora resetar

### ISSUE THREAD

**Issue by joaovcbarboza** [cwi-reset/edicao-04-level-1#29]
Bom dia, pessoal. Me chamo joão e venho buscando desenvolver minhas hards e softs skills na área de Ti. o programa da cwi seria uma grande oportunidade para este feito.
Desejo boa sorte para todos!!

**Comment by gustavoullmann** [comment]
Oi @joaovcbarboza! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
