### ISSUE TITLE
Link da live da última aula 

### ISSUE THREAD

**Issue by Laurimiguel** [cwi-reset/edicao-04-level-1#291]
Bom dia. Ainda não saiu o link da última aula de sexta feira né? Estou no aguardo

**Comment by Renatalealmoreira** [comment]
Se não recebeu ainda o e-mail, você pode consultar o link da live no seu GITHUB no tópico Calendário de LIVES. Espero que consiga 🙏

**Comment by joprestes** [comment]
Bom dia Lauri!
O calendário das lives, bem como os links para sua  [visualização estão neste local]( https://github.com/cwi-reset/edicao-04-level-1)
Abaixo do cronograma, quase no finzinho da página,como podemos visualizar abaixo:
![image](https://user-images.githubusercontent.com/76666518/189643044-5dfa4fd6-12bf-4b06-84d8-30f6c7e808ca.png)
