### ISSUE TITLE
[Avaliações Lives] Não recibemento de Emails

### ISSUE THREAD

**Issue by Allemaun** [cwi-reset/edicao-04-level-1#292]
Bom dia @guilhermewmuller 

Não recebi o formulário de avaliação das últimas lives no meu Email, e nos Spans eles não estão.
Se puderem me dar um suporte nessa parte ficarei agradecido.

**Comment by NicoledeRossi** [comment]
Estava mesmo procurando o link para avaliação.  Eles passaram no Chat no fim da live, mas não peguei.  E não recebi o e-mail também.   
Hoje estou focana nas aulas de lógica de programação, que estão sendo muito boas.

**Comment by Allemaun** [comment]
Boa @NicoledeRossi 

Vamos aguardar o retorno deles sobre o Email.

**Comment by guilhermewmuller** [comment]
Olá, pessoal! bom dia 
Estamos preparando o envio dos emails :)

Até lá, não esqueçam que os links também estão sempre disponíveis aqui no repositório do GitHub.
https://github.com/cwi-reset/edicao-04-level-1/blob/main/README.md#calend%C3%A1rio-de-lives

**Comment by NicoledeRossi** [comment]
ok. obrigado
