### ISSUE TITLE
[Módulo 6 - GitHub]

### ISSUE THREAD

**Issue by giovanekochhann** [cwi-reset/edicao-04-level-1#299]
Pessoal preciso de uma ajuda dos meus futuros colegas na CWI! 

Trabalhei com programação há muitos anos, nunca soube da existencia do GitHub,  mas após ver as aulas do módulo e brincar um pouco na plataforma adorei, agora é possivel controlar a evolução do desenvolvimento!

Fiz minha conta, e toda a configuração usando terminal no linux Ubuntu. Criei 3 repositorios para projetos que ja estava rodando, e fiz alguns testes. Mas estou esbarrando em um problema de compreensão do funcionamento da ferramenta.
Meus repositorios são:
https://github.com/giovanekochhann/TradingResultsWebsite
https://github.com/giovanekochhann/cTraderBots
https://github.com/giovanekochhann/tradetracking

Ao configurar via terminal não sei se estou fazendo push em todos os projetos juntos ou se devo configurar um de cada vez.
Se a configuração for individual dando o comando dentro de cada pasta preciso criar chaves SSH individuais?
e sobre as branches? eu devo fazer uma para cada máquina que uso para programar ou uma para cada projeto?

**Comment by Allemaun** [comment]
Boa tarde @giovanekochhann 

Estou longe de ter dominado o GitHub, então eu sempre add tudo do meu projeto e após isso faço o push.
Depois de clonado tu não precisa fazer mais nada, apenas abrir o GitBash na pasta que você está salvando teus projetos, add as modificações e fazer os commits.
Sobre os branchs eu entendo que ele seria mais útil no caso de você precisar refazer ou corrigir um código que está rodando sem precisar mexer no que está funcionando até estar tudo ok pra atualizar.

**Comment by cristianodc** [comment]
O push para o repositório é feito um por vez, por exemplo se você faz alterações em 1 arquivo ou em 10 arquvos  do teu projeto após você  commitar as alterações, e fizer o push será valido para todos os arquivos alterados.  
A chave é uma maquina (**_tenho uma duvida pequena aqui_**), Mas eu por exemplo uso a **mesma** chave em todos os meu projetos no mesmo PC;

**Comment by fmarga** [comment]
A chave SSH serve para identificar a máquina da qual você está realizando os commits, então não seria necessário ter mais de uma se você utiliza sempre a mesma máquina para desenvolver seus projetos. 
Já sobre as branches, você pode ter quantas forem necessárias para um repositório, geralmente se utiliza de branches quando o projeto é em grupo e cada pessoa vai desenvolver uma parte diferente do código, ou então quando você quer realizar alterações no código mas quer garantir que uma versão dele esteja funcionando e organizada. Após finalizadas as tarefas geralmente se submete as alterações dessa branch para a branch main, que é onde ficará a versão "final" ou mais atualizada do projeto

**Comment by giovanekochhann** [comment]
@Allemaun @fmarga @cristianodc obrigado pelos esclarecimentos, compreendi um pouco melhor porém ainda estou me batendo por aqui.

Vejam só, quando uso o comando abaixo, dentro da pasta do meu projeto de nome ("tradetracking")
git remote add origin git@github.com/giovanekochhann/tradetracking

Estou definindo pro git que a pasta que estou usando para enviar o comando é a pasta origin desse meu repositorio.
Quando faço:
git push -u origin master
Estou atualizando apenas esse repositorio, nao atualizo os demais. É isso? Caso eu deseje atualizar o outro repositorio de nome cBots_cTrader, devo repetir o comando configurando o origin:

git remote add origin git@github.com/giovanekochhann/cBots_cTrader

p depois fazer novo push?

**Comment by cristianodc** [comment]
Isso mesmo, vai sempre usar esse comando, olha quando tu for criar um novo repositório o git ja mostra os passos basicos
o basico é isso mesmo
git remote add origin [git@github.com](mailto:git@github.com)/giovanekochhann/cBots_cTrader
git remote add origin [git@github.com](mailto:git@github.com)/giovanekochhann/cBots_cTrader01
e assim por diante para cada repositório lembrando que se quiser ou pode trocar a **palavra oringin por outra**
 git remote add **_cBots_cTrader_** [git@github.com](mailto:git@github.com)/giovanekochhann/cBots_cTrader03
depois o push
git push -u **_cBots_cTrade_** master

**Comment by giovanekochhann** [comment]
@cristianodc 
Após enviar o ultimo issue, verifiquei que todos os arquivos no meu computador estavam up to date. Resolvi apagar os repositorios no github e fazer novamente a configuração para entender.

Acabei de finalizar a criação dos tres respositorios e já fiz todos os pushs... pensa num cara faceiro :p

Como fiz o processo 3x ficou bem claro, usei como voce comentou o basico que o próprio git expõe quando finaliza a criação do repositorio. Depois que vi tua resposta elucidou ainda mais, porque me dei conta que minha maior confusão era chamar todos os repo de ORIGIN, com a tua dica dei "nomes aos bois" agora posso tratar como projetos separados, como queria desde o começo e não sabia como.

Muito obrigado a todos, agora vou ver como fecha esse issue...
