### ISSUE TITLE
Lives até o momento.

### ISSUE THREAD

**Issue by igoroliveirasilva** [cwi-reset/edicao-04-level-1#301]
Live 1 - https://vimeo.com/743407625/07db9090ff
Live 2 -´https://vimeo.com/744736042/4cdf0d0ce0
Live 3 - https://vimeo.com/744736353/d3fc2e6f9a

**Comment by joprestes** [comment]
Obrigada pela iniciativa @igoroliveirasilva , 

O cronograma e disponibilização de links estão centralizados aqui: [LINK](https://github.com/cwi-reset/edicao-04-level-1)
![image](https://user-images.githubusercontent.com/76666518/190151477-8e780f2c-4d77-4215-896d-1788e3fd2051.png)


Reset, restart, go! 🚀

**Comment by igoroliveirasilva** [comment]
Show de bola.
