### ISSUE TITLE
[MODULO 4] Aula #03

### ISSUE THREAD

**Issue by NatoCorrea** [cwi-reset/edicao-04-level-1#306]
Sempre que eu entro no editor de texto no GIT, fico preso e não consigo sair... tenho que fechar o Git e começar novamente. Na aula ele fala em dar ";qw" faço isso, vejo que ele salva mas continua preso la no editor.

**Comment by NatoCorrea** [comment]
Acredito ter encontrado a solução já... Quando chegar em casa a tarde, tento e se de certo, deixo aqui. Valeu

**Comment by rguedes28** [comment]
Oii Nato, tudo bem... para sair do editor você primeiro tem q sair do modo de insert com a tecla "esc", depois vai em sequencia colocar o : (dois pontos), o "w", e o "q" nessa ordem.... vê se consegue ai se não tento te mostrar de outra forma..

**Comment by NatoCorrea** [comment]
Fala, Rafa... Tudo bem contigo? Eu estava fazendo esse processo ai mas mesmo assim não estava funcionando. Dei uma "googlada" (hehehe) por aqui e encontrei uma informação mandando eu clicar "ZZ" (2 vezes a letra Z, maiúscula) e funcionou.


Agora tou preso em outro problema... tento dar um push e o git sempre pede usuário e senha mesmo com a chave SSH cadastrada e com isso o push falha a todo momento.

Obrigado pela disponibilidade e ajuda.
