### ISSUE TITLE
Aula 01 - Testes Automatizados em Aplicações Web - instalação cypress.

### ISSUE THREAD

**Issue by superjhonatan** [cwi-reset/edicao-04-level-1#307]
bom dia pessoal.

estou com um problema para instalar o cypress.
![image](https://user-images.githubusercontent.com/112219528/190397083-4824322b-391d-4064-a3f2-fac50e8579d0.png)

depois de seguir os passos para a instalação, Quando tento executar o comando:

```
npx cypress open

```

esse erro acontece e não abre:

![image](https://user-images.githubusercontent.com/112219528/190397386-d9da3390-1094-449b-a2bc-0e2c4960a89e.png)

já dei uma pesquisada na iternet, segui todos os tutoriais que encontrei mas não consegui resolver o problema.

**Comment by EullerLisowski** [comment]
Bom dia, Jhonatan.

Tu consegue passar um passo a passo um pouco mais detalhado? Talvez com um print mostrando o resultado de cada comando antes do cypress open?

Eu vi na segunda linha do teu terminal escrito `instal` quando deveria ser `install`, pode ser que alguma letra foi errada nos passos anteriores.

Os comandos a serem executados antes do cypress open são:
`npm init --yes` e `npm install -D cypress `

![image](https://user-images.githubusercontent.com/11744916/190418550-04110efa-730f-4c61-aa79-3a86f30464c5.png)

**Comment by superjhonatan** [comment]
@EullerLisowski, os comandos que eu escrevi estão selecionados em cada print.

comando 1: ``npm init --yes``

![image](https://user-images.githubusercontent.com/112219528/190420843-d9399c99-0f30-4413-8942-9db167d9771c.png)

comando 2:``npm install -D cypress``

![image](https://user-images.githubusercontent.com/112219528/190421900-0b631b5b-2896-4ae0-9454-11d5a62c92b4.png)

comando 3:``npx cypress open``

![image](https://user-images.githubusercontent.com/112219528/190422531-32520b03-bbf5-4715-96ba-6281c6775dde.png).

desde já agradeço pela ajuda @EullerLisowski :)

**Comment by EullerLisowski** [comment]
Certo, tu tem permissão de administrador da máquina?
Consegue testar abrindo o vscode como administrador e com um terminal de administrador?

**Comment by superjhonatan** [comment]
consigo

**Comment by Allemaun** [comment]
Bom dia @superjhonatan 

Encontrei essa reposta a uma pergunta aparentemente igual a tua:
https://cursos.alura.com.br/forum/topico-configurando-o-ambiente-nao-apareceu-o-arquivo-package-json-163297

**Comment by superjhonatan** [comment]
@EullerLisowski , consegui resolver o problema da execução fazendo a instalação da versão 10.0 usando o comando:`npm install -D cypress@10.0.0`. Então caso alguém tenha o mesmo problema que eu tenta instalar a versão 10.0 

@Allemaun embora eu tenha conseguido insalar e executar o cypress continuo com o problema do arquivo `cypress.json` que não aparece pra mim após a instalação e execução. os arquivos:`package-lock.json` e `package.json`, aparecem como pode ser visto na imagem abaixo. só esse `cypress.json`, que não aparece.

![image](https://user-images.githubusercontent.com/112219528/190446187-99f60b02-a62c-4e0a-8142-907f031ea7f9.png)

**Comment by EullerLisowski** [comment]
@superjhonatan que bom que tu conseguiu resolver.

Sobre o `cypress.json` esse arquivo não existe mais a partir da versão 10 ele foi substituído pelo `cypress.config.js`.

Tu pode fazer a configuração executando `npx cypress open`.

E a partir da tela seguindo os passos abaixo:

![image](https://user-images.githubusercontent.com/11744916/190465949-4cef9167-6d1a-44a4-bd33-5b299bb61e87.png)

Clica em E2E Testing

Depois na tela seguinte clica em continue:

![image](https://user-images.githubusercontent.com/11744916/190466599-4702d168-907e-4d25-9043-cd0b33376156.png)

Aí tua pasta deve estar assim:
![image](https://user-images.githubusercontent.com/11744916/190466763-9eb9f436-0b9e-4114-96b3-1eedac7365a9.png)

**Comment by Allemaun** [comment]
@superjhonatan 

Que bom que resolveu, estava olhando aqui e pelo que vi esse erro é no windows,
Caso queira dar uma conferida no assunto da minha pesquisa eis o link: 

https://www.youtube.com/watch?v=K0rS3MUDCRg

Olhei vários pra ver se falariam a mesma coisa, mas não testei pois não tive o problema em questão.

**Comment by superjhonatan** [comment]
@EullerLisowski , deu tudo certo seguindo o passo a passo que você postou, obrigado.
@Allemaun , tu tem sido um cara muito presente nas issues, essa já é a terceira ou quarta vez que tu tira um pouco do teu tempo pra me ajudar com alguma coisa, obrigado. Eu consegui resolver o problema mas vou assistir ao vídeo mesmo assim,  conhecimento nunca é demais.

como o problema foi resolvido vou fechar a issue.

obrigado mais uma vez aos dois 🤜🤛

**Comment by BentoMaciel** [comment]
Boa noite Colegas!
Tive problemas com a criação da pasta "integration" alguém mais nessa situação?
