### ISSUE TITLE
Git de outro usuário - como alterar usuário do Git

### ISSUE THREAD

**Issue by brunafmonique** [cwi-reset/edicao-04-level-1#308]
Bom dia,
Baixei o Git conforme solicitado, porém ele está com outra conta de usuário. Já olhei vários tutoriais mas não consegui incluir meu usuário, permanece o usuário antigo. Alguém consegue me ajudar?

**Comment by Allemaun** [comment]
Olá bom dia @brunafmonique 

Encontrei essa matéria no google, espero que ela  seja útil:
https://coffops.com/alteracao-de-usuario-git/

**Comment by joprestes** [comment]
@brunafmonique  boa noite, 
Conseguir efetuar a troca das credenciais de usuário no seu GIT?

Reset, restart, go! 🚀

**Comment by brunafmonique** [comment]
Segui todo o passo a passo, mas permanece com outro nome. Acredito que o GIT tenha ficado com meu nome e e-mail, porém no meu terminal ainda permanece outro nome por ser este o usuário do Windows. É possível?

**Comment by lipecanon** [comment]
> Segui todo o passo a passo, mas permanece com outro nome. Acredito que o GIT tenha ficado com meu nome e e-mail, porém no meu terminal ainda permanece outro nome por ser este o usuário do Windows. É possível?

Buenas @brunafmonique!

Você rodando o comando git config --global user.name, o nome do seu usuário aparece corretamente? Caso não apareça, tente rodar git config --global user.name " nome do seu usuario" e verifique novamente. Caso ainda tenha problemas, verifica se na tua máquina existe o .gitconfig no teu diretório $HOME ou na raiz da tua instalação do GIT (/etc/gitconfig).

**Comment by brunafmonique** [comment]
Rodei git config --global user.name e apareceu o usuário correto.
Muito obrigada pelo auxilio ;)
