### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by brunogs97** [cwi-reset/edicao-04-level-1#31]
Olá pessoal. Me chamo Bruno, tenho 25 anos e atualmente trabalho na área de usinagem.

**Comment by Fred12Silva** [comment]
Bom dia amigos, sou Frederico Silva, tenho 32 anos e venho da área financeira.

**Comment by gustavoullmann** [comment]
Oi @brunogs97! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
