### ISSUE TITLE
[Módulo 3] Aula 06 -  Condicionais - Exercício do IMC - Dúvida

### ISSUE THREAD

**Issue by CamilaGoulart** [cwi-reset/edicao-04-level-1#313]
Olá pessoal!
Estou fazendo o exercício do IMC, e encontrei um Bug no meu código, mas não estou conseguindo identificar o erro.
Se alguém puder me ajudar.

No caso, o erro é o seguinte, testando diferentes IMCs, vi que acima de 40, não está exibindo a mensagem que coloquei, está colocando a outra mensagem.
![Exercício](https://user-images.githubusercontent.com/112297674/190484650-effb055b-c052-40a3-8b30-c71045933e6c.jpg)

```javascript

peso = 150
altura = 1.79
imc = peso/altura**2

classificacao = ""
if (imc <18.5)
{
  classificacao = "Magreza"
}
else if (imc <=24.99){
  classificacao = "Normal"
}
else if (imc <=29.99){
  classificacao = "Sobrepeso"
}
else if (imc <=39,99){
  classificacao = "Obesidade"
}
else {(imc >= 40.00)
  classificacao = "Obesidade grave"
}
console.log("Seu IMC é", imc)
console.log ("Sua classificação é", classificacao)
  
switch (classificacao){
  case "Sobrepeso":
    console.log ("Cuidado! Você está acima do peso recomendado pela OMS.")
    break;

  case "Obesidade":
    console.log ("Cuidado! Você está acima do peso recomendado pela OMS.")
    break;

  case "Obesidade grave":
    console.log ("É importante procurar um médico para avaliar sua saúde.")
    break;
}

**Comment by Allemaun** [comment]
Boa tarde @CamilaGoulart 

Dá uma olhada no else ele está com os colchetes antes dos parênteses.
Existe uma grande chance de ser este o problema.

**Comment by CamilaGoulart** [comment]
> 

Muito obrigada!
Na verdade, identifiquei que não preciso colocar valor do imc no else, mas o erro não estava ali, estava no "39,99" que coloquei errado, coloquei uma vírgula ao invés do ponto 39.99.

```javascript

peso = 150
altura = 1.79
imc = peso/altura**2

classificacao = ""
if (imc <18.5)
{
  classificacao = "Magreza"
}
else if (imc <=24.99){
  classificacao = "Normal"
}
else if (imc <=29.99){
  classificacao = "Sobrepeso"
}
else if (imc <=39.99){
  classificacao = "Obesidade"
}
else {
  classificacao = "Obesidade grave"
}
console.log("Seu IMC é", imc)
console.log ("Sua classificação é", classificacao)
  
switch (classificacao){
  case "Sobrepeso":
    console.log ("Cuidado! Você está acima do peso recomendado pela OMS.")
    break;

  case "Obesidade":
    console.log ("Cuidado! Você está acima do peso recomendado pela OMS.")
    break;

  case "Obesidade grave":
    console.log ("É importante procurar um médico para avaliar sua saúde.")
    break;
}

**Comment by Allemaun** [comment]
Estava corrigindo os colchetes para chaves e acrescentando esse detalhe
Mas que bom que conseguiu resolver

**Comment by CamilaGoulart** [comment]
> Estava corrigindo os colchetes para chaves e acrescentando esse detalhe Mas que bom que conseguiu resolver

Muito obrigada pela disponibilidade!
