### ISSUE TITLE
RESET

### ISSUE THREAD

**Issue by SabrinaBritto** [cwi-reset/edicao-04-level-1#319]
Sabrina Brito, sou da área da saúde (Tec de enfermagem e Fisioterapeuta) e entrando agora para a área da TI através do RESET. Boraaa

**Comment by joprestes** [comment]
Oi @SabrinaBritto ! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos 🚀
