### ISSUE TITLE
Apresentação Reset

### ISSUE THREAD

**Issue by Fred12Silva** [cwi-reset/edicao-04-level-1#32]
Bom dia amigos, me chamo Frederico Silva, tenho 32 anos e venho da área financeira.

**Comment by gustavoullmann** [comment]
Oi @Fred12Silva! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
