### ISSUE TITLE
Level 1 - Módulo Lógica de Programação - Exercício Final questão #1

### ISSUE THREAD

**Issue by razelaguimaraes** [cwi-reset/edicao-04-level-1#321]
Bom dia, 👍 
Acredito que exista uma ambiguidade na questão 1 do exercício final do módulo 3.

![image](https://user-images.githubusercontent.com/112423572/190863471-ba1fddc1-7c87-43ec-b2cd-30752312b07e.png)

A variável boolean aceita valores verdadeiro e falso (true e false) minúsculo. Porém, nas alternativas não consta essa opção. Consta apenas em maiúsculo, e isso faz a diferença conforme testes realizados no repl.it.

![image](https://user-images.githubusercontent.com/112423572/190863552-26ff6361-404f-4b64-b724-2386016f3c1c.png)

Logo, a alternativa correta seria (nenhuma das alternativas). 
Porém, a alternativa correta do questionário é (TRUE / FALSE).

Seria interessante deixar essa alternativa em minúsculo.

**Comment by RebecaPR** [comment]
Olá @razelaguimaraes tudo bem? 

Acho que não há erro na questão se pararmos pra notar que todas as demais alternativas tb estão em caixa alta exceto as frases, dessa forma seria como se não houvesse diferenças entre elas, apena a formatação da questão mesmo, por isso, que não mudaram a resposta... não sei..

**Comment by Allemaun** [comment]
Boa tarde @razelaguimaraes 

A questão nem é pelo CapsLock ativado, pois variável booleana retorna apenas True e False.

**Comment by jgusson1979** [comment]
eu coloquei yes e No e errei

**Comment by patyfil** [comment]
também fui pela lógica de que as outras respostas estão em maiúsculas, mas concordo com a [razelaguimaraes](https://github.com/razelaguimaraes), essa questão deveria ser corrigida pois deixa na dúvida. Até porque tem algumas linguagens que aceitam maiúscula, python por exemplo começa com a letra maiúscula (True, False).

**Comment by joprestes** [comment]
@patyfil @jgusson1979 @razelaguimaraes 
Bom dia!
Vejam  que a questão questiona o  **_TIPO_** de de valores que  uma variável do tipo boolean armazena e não o **_valor literal_** que ela pode armazenar.

Espero ter auxiliado.

Reset, restart, go! 🚀

**Comment by razelaguimaraes** [comment]
Olá @joprestes, obrigada pelo retorno.
