### ISSUE TITLE
Duvida na instalação do cypress test, vision video code

### ISSUE THREAD

**Issue by tatimirandinha** [cwi-reset/edicao-04-level-1#322]
Boa tarde,
estou com essa mensagem na tela e não sei o que fazer.
para dar continuidade....

Windows PowerShell
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

Experimente a nova plataforma cruzada PowerShell https://aka.ms/pscore6

PS C:\Users\tatim\OneDrive\Área de Trabalho\Cypress>

**Comment by patyfil** [comment]
Boa noite [tatimirandinha](https://github.com/tatimirandinha)!
sua dúvida seria na instalação do Cypress ou do VsCode (Visual Studio Code)? Seria melhor você detalhar mais ou mandar um print, mas pelo o que você escreveu, parece que você está com dúvida se essa tela está correta, pela mensagem que vc mandou, está tudo certo, agora é só digitar o comando depois da sua útlima linha:

PS C:\Users\tatim\OneDrive\Área de Trabalho\Cypress>npm install -D cypress

Esse comando instala o cypress, mas antes digite o comando: npm init –yes

**Comment by Askalor** [comment]
> Boa tarde, estou com essa mensagem na tela e não sei o que fazer. para dar continuidade....
> 
> Windows PowerShell Copyright (C) Microsoft Corporation. Todos os direitos reservados.
> 
> Experimente a nova plataforma cruzada PowerShell https://aka.ms/pscore6
> 
> PS C:\Users\tatim\OneDrive\Área de Trabalho\Cypress>

Oi @tatimirandinha, essa é uma mensagem padrão de quando você abre o terminal. É só ignorar ela e seguir com os comandos que o Samuel faz no vídeo em que ele ensina a iniciar um projeto e fazer a instalação do Cypress. Ele ensina a fazer isso a partir dos 19:25 desse [vídeo](https://youtu.be/fNcFvZv1YmY?t=1165). Só preste atenção se você já instalou as coisas necessárias no pré-requisito que ele demonstra um pouco antes no vídeo.

**Comment by Luzinei** [comment]
Boa noite, pessoal! Acredito que estou com o mesmo problema da Tati, podem me auxiliar, por gentileza, segue print anexo. No terminal não está limpo como no do Samuel. 
[Terminal.docx](https://github.com/cwi-reset/edicao-04-level-1/files/9595566/Terminal.docx)

Não consigo usar os comandos devido a mensagem abaixo, tenho que baixar esse PowerShell? pois não consegui.
Instale o PowerShell mais recente para obter novos recursos e aprimoramentos! https://aka.ms/PSWindows

Fico no aguardo e a disposição!

**Comment by Askalor** [comment]
> Boa noite, pessoal! Acredito que estou com o mesmo problema da Tati, podem me auxiliar, por gentileza, segue print anexo. No terminal não está limpo como no do Samuel. [Terminal.docx](https://github.com/cwi-reset/edicao-04-level-1/files/9595566/Terminal.docx)
> 
> Não consigo usar os comandos devido a mensagem abaixo, tenho que baixar esse PowerShell? pois não consegui. Instale o PowerShell mais recente para obter novos recursos e aprimoramentos! https://aka.ms/PSWindows
> 
> Fico no aguardo e a disposição!

Creio que essa mensagem só queira dizer que você não deve ter a versão mais atualizada dele. Sobre os comandos, você tentou usar no terminal? Pois eles estão escritos no arquivo que você criou, e não no terminal. Seu terminal não tem nenhum comando executado.

E ele está apontando para a pasta padrão do One Drive. Eu sugiro você criar uma pasta em si para seu projeto, e então usar os comandos no terminal para iniciar o projeto nessa pasta

**Comment by Luzinei** [comment]
Boa noite! conseguir resolver meu problema, não estava encontrando a opção de abrir um novo projeto, logo após abrir um novo terminal ficou disponível a opção criar novo projeto, a partir dai conseguir rodar os comandos do video. Obrigada!

**Comment by joprestes** [comment]
@tatimirandinha  Bom Dia!
Conseguiu dar prosseguimento em sua instalação?

Reset, restart, go! 🚀

**Comment by tatimirandinha** [comment]
Bom dia!!!Não... ☹ Até troquei de computador e tb apresentou a mesma mensagem. Tatiana Enviado do Email para Windows De: Joelma PrestesEnviado:segunda-feira, 19 de setembro de 2022 08:45Para: cwi-reset/edicao-04-level-1Cc:Tatiana Miranda; MentionAssunto: Re: [cwi-reset/edicao-04-level-1] Duvida na instalação do cypress test, vision video code (Issue ***@***.*** Bom Dia!Conseguiu dar prosseguimento em sua instalação?Reset, restart, go! 🚀—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by joprestes** [comment]
@tatimirandinha Você tentou rodar os comandos que são apresentados no vídeo e eles não funcionaram?
Ou a mensagem aparece quando voê abre o termianl, e devido a essa ocorrência  você não dá andamento na instalação?
Por ficar na  dúvida e como proceder?

**Comment by tatimirandinha** [comment]
OiFiz a instalação, porem qdo vou iniciar o cypress , aparece a mensagem e não consigo dar continuidade. Fiz o passo a passo, conforme o vídeo. No momento estou no trabalho, só consigo ver a noite.  Quando chegar em casa, te envio o passo a passo que fiz, pode ser? Agradeço a atenção. Tatiana Miranda Enviado do Email para Windows De: Joelma PrestesEnviado:segunda-feira, 19 de setembro de 2022 09:31Para: cwi-reset/edicao-04-level-1Cc:Tatiana Miranda; MentionAssunto: Re: [cwi-reset/edicao-04-level-1] Duvida na instalação do cypress test, vision video code (Issue ***@***.*** Você tentou rodar os comandos que são apresentados no vídeo e eles não funcionaram?Ou a mensagem aparece quando voê abre o termianl, e devido a essa ocorrência você não dá andamento na instalação?Por ficar na dúvida e como proceder?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by tatimirandinha** [comment]
Sim, qdo  abro o terminal , não consigo dar continuidade. Tatiana Enviado do Email para Windows De: Joelma PrestesEnviado:segunda-feira, 19 de setembro de 2022 09:31Para: cwi-reset/edicao-04-level-1Cc:Tatiana Miranda; MentionAssunto: Re: [cwi-reset/edicao-04-level-1] Duvida na instalação do cypress test, vision video code (Issue ***@***.*** Você tentou rodar os comandos que são apresentados no vídeo e eles não funcionaram?Ou a mensagem aparece quando voê abre o termianl, e devido a essa ocorrência você não dá andamento na instalação?Por ficar na dúvida e como proceder?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by joprestes** [comment]
@tatimirandinha  Certo, fico no aguardo.

Reset, restart, go! 🚀

**Comment by tatimirandinha** [comment]
Ok. Tatiana Enviado do Email para Windows De: Joelma PrestesEnviado:segunda-feira, 19 de setembro de 2022 10:10Para: cwi-reset/edicao-04-level-1Cc:Tatiana Miranda; MentionAssunto: Re: [cwi-reset/edicao-04-level-1] Duvida na instalação do cypress test, vision video code (Issue ***@***.*** Certo, fico no aguardo.Reset, restart, go! 🚀—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by tatimirandinha** [comment]
OI ESSA MENSAGEM, APARECE QUANDO “NOVO TERMINAL”  O Windows PowerShellCopyright (C) Microsoft Corporation. Todos os direitos reservados. Instale o PowerShell mais recente para obter novos recursos e aprimoramentos! https://aka.ms/PSWindows PS C:\Users\sinpr>   NÃO SEI O QUE ESCREVER AQUI    Enviado do Email para Windows De: Joelma PrestesEnviado:segunda-feira, 19 de setembro de 2022 10:10Para: cwi-reset/edicao-04-level-1Cc:Tatiana Miranda; MentionAssunto: Re: [cwi-reset/edicao-04-level-1] Duvida na instalação do cypress test, vision video code (Issue ***@***.*** Certo, fico no aguardo.Reset, restart, go! 🚀—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by darlanmouratabosa** [comment]
Olá. Vou aproveitar essa issue já aberta para postar meu problema

Na tentativa de instalação do Cypress, seguindo o comando:
npm install -D cypress

O powershell abre e fecha imediatamente, sem nenhuma mudança de arquivos e/ou pastas.

Pesquisando, achei esse outro comando:
npm install cypress --location=global

Ele abre o powershell e acontece um processo de instalação parecido com o do vídeo, porém ao terminar, continua sem mudanças. Não aparece o node_modules nem nada.

Qual pode ser o erro?

**Comment by lipecanon** [comment]
> Olá. Vou aproveitar essa issue já aberta para postar meu problema
> 
> Na tentativa de instalação do Cypress, seguindo o comando: npm install -D cypress
> 
> O cmd abre e fecha imediatamente, sem nenhuma mudança de arquivos e/ou pastas.
> 
> Pesquisando, achei esse outro comando: npm install cypress --location=global
> 
> Ele abre o cmd e acontece um processo de instalação parecido com o do vídeo, porém ao terminar, continua sem mudanças. Não aparece o node_modules nem nada.
> 
> Qual pode ser o erro?

Opa @darlanmouratabosa buenas?

Se tu excluir o package.json da pasta e executar o comando npm init e depois npm install cypress --save-dev, ocorre a mesma situação?

**Comment by tatimirandinha** [comment]
Boa noite!Essa mensagem qdo abro o terminal....  Windows PowerShellCopyright (C) Microsoft Corporation. Todos os direitos reservados. Experimente a nova plataforma cruzada PowerShell https://aka.ms/pscore6 PS C:\Users\tatim\OneDrive\Área de Trabalho\Cypress> Não sei o que fazer..... Tatiana   Enviado do Email para Windows De: Filipe ToniazzoEnviado:segunda-feira, 19 de setembro de 2022 19:04Para: cwi-reset/edicao-04-level-1Cc:Tatiana Miranda; MentionAssunto: Re: [cwi-reset/edicao-04-level-1] Duvida na instalação do cypress test, vision video code (Issue #322) Olá. Vou aproveitar essa issue já aberta para postar meu problemaNa tentativa de instalação do Cypress, seguindo o comando: npm install -D cypressO cmd abre e fecha imediatamente, sem nenhuma mudança de arquivos e/ou pastas.Pesquisando, achei esse outro comando: npm install cypress --location=globalEle abre o cmd e acontece um processo de instalação parecido com o do vídeo, porém ao terminar, continua sem mudanças. Não aparece o node_modules nem nada.Qual pode ser o erro?Opa @darlanmouratabosa buenas?Se tu excluir o package.json da pasta e executar o comando npm init e depois npm install cypress --save-dev, ocorre a mesma situação?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by eshic** [comment]
Boaaaa então, o Cypress teve atualização de versão desde a gravação da aula, mas está correto dessa forma mesmo, com uma versão maior, pode seguir com os estudos \o/
