### ISSUE TITLE
Apresentação programa Reset

### ISSUE THREAD

**Issue by jpteles1410** [cwi-reset/edicao-04-level-1#33]
Bom dia Pessoal!
Sou João Paulo Teles, sou Analista de Negócios e trabalho com sistemas de gestão ERP desde 2003. Estou buscando neste programa RESET como uma repaginação profissional dentro da área que venho trabalhando a tanto tempo e que realmente me sinto muito a vontade e feliz! Desejo sucesso a todos! E espero poder dar aquele RESET com jeitinho de UPDATE em minha carreira profissional!

**Comment by gustavoullmann** [comment]
Oi @jpteles1410! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
