### ISSUE TITLE
Todo. comando "context" não funciona!

### ISSUE THREAD

**Issue by BentoMaciel** [cwi-reset/edicao-04-level-1#336]
![image](https://user-images.githubusercontent.com/112488425/191137890-8900c2e3-c75f-490f-8b00-049c962118b8.png)

quando digito o comando " context" ele não assume a forma correta em relação a estrutura, só abre outros comandos similares. Será que não instalei algum pacote?

**Comment by Askalor** [comment]
Ele não precisa abrir, é só você completar a mão. Mas sim, normalmente os completes são plugins instalados

**Comment by BentoMaciel** [comment]
@Askalor sabe como eu posso baixar esse pacote de plugins?

**Comment by Askalor** [comment]
> @Askalor sabe como eu posso baixar esse pacote de plugins?

Sinceramente não sei qual é. Mas o Samuel (do canal do vídeo) tem um outro vídeo no canal dele onde ele mostra os plugins que usa. Talvez você encontre lá

**Comment by BentoMaciel** [comment]
@Askalor obrigado!
