### ISSUE TITLE
"Todo.spec.js" ou "Todo.cy.js"?

### ISSUE THREAD

**Issue by BentoMaciel** [cwi-reset/edicao-04-level-1#337]
Não consigo rodar o Todo.spec.js.
O mesmo se que aparece no Cypress quando coloco a extensão (.spec.js).
Já quando modifico para (.cy.js), ele aparece no Cypress porém algo no código está errado e não consegui identificar. Talvez seja a tal da "Arrow function" que acredito não estar correto.

```Context('TodoMVC', () => {
        it('adicionar um nova tarefa', () => {
            cy.visit("https://todomvc-app-for-testing.surge.sh/");

        });
    });
```

![image](https://user-images.githubusercontent.com/112488425/191147415-c6097b6c-5a90-4db3-9202-e17935e9df2a.png)

**Comment by CamilaGoulart** [comment]
Olá, tudo bem? Demorei para entender esse negocio do spec.js e cy.js, no vídeo o Samuel utiliza o spec, mas a versão dele é antiga, na versão 10 que estamos usando, mudou as pastas, usa o cy.js ou faz como na live de hoje, que mostraram como mudar a configuração. Eu acabei de copiar tudo certinho como o Samuel fez no vídeo, e deu certo. Aparentemente o que difere o seu do meu, é esse ";" que está depois do site, mas não sei se faz diferença. 
![image](https://user-images.githubusercontent.com/112297674/191148801-46981717-0c63-4dad-ab1d-1161a92efb77.png)

segue o código:

```
context('TodoMVC', () => {
    it('Adicionar uma nova tarefa', () => {
        cy.visit ("https://todomvc-app-for-testing.surge.sh/")

        cy.get ("input.new-todo").type ("Estudar automação de testes{enter}")

        //validação/garantia
        
        cy.get ("ul.todo-list li").should("have.length", 1)
    });
    
});

**Comment by Askalor** [comment]
A `.spec.js` é para a versão antiga do Cypress. A `.cy.js` é para a versão nova. É possível fazer o .spec.js funcionar na versão atual, mas acho desnecessário. Na live de hoje foi demonstrado como fazer isso. É útil caso você esteja usando algum projeto antigo e não quer ter que renomear os arquivos.

Já o seu código é por que você está dando espaço depois dos seus comandos. Deve ser sem espaço como demonstrado na resposta da Camila

@CamilaGoulart O ponto e virgula não faz diferença. Algumas linguagens de programação requerem que você use `;` no final de uma linha de código para demonstrar que aquele código encerrou ali. No Javascript isso não é obrigatório. Creio que o Samuel use por costume de outras linguagens.

**Comment by BentoMaciel** [comment]
Segue mensagem no Cypress.

66ms
An uncaught error was detected outside of a testfailed
No commands were issued in this test.
ReferenceError
The following error originated from your test code, not from Cypress.

> Context is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
[cypress/e2e/todo.cy.js:1:1](https://todomvc-app-for-testing.surge.sh/__/#)
> 1 | Context('TodoMVC', () => {
    | ^
  2 |     it('Adicionar um nova tarefa', () => {
  3 |         cy.visit("https://todomvc-app-for-testing.surge.sh/")
  4 |

**Comment by Askalor** [comment]
@BentoMaciel Provavelmente é pelo seu C estar maiúsculo.

**Comment by BentoMaciel** [comment]
@Askalor sim meu querido! Cara, eu tava bem loco, colocando o código da @CamilaGoulart em contra-prova e nada, até que achei o bendito. mas... enfim.... erro de novato.

Muito obrigado pela ajuda dos colegas!
