### ISSUE TITLE
Jonny Santos

### ISSUE THREAD

**Issue by jonnyreset** [cwi-reset/edicao-04-level-1#35]
Olá pessoal .! Me chamo Jonny  e  estou muito feliz em participar dessa edição da CWI , sempre atuei na área da mecânica e estou buscando trilhar um novo caminho na área da TI , espero conseguir ir a algum lugar rsrsrsr. Desejo que Deus abençoe a todos os participantes e também a todos que formam a CWI, e vamos seguir para as próximas etapas com fé em DEUS.

**Comment by gustavoullmann** [comment]
Oi @jonnyreset! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
