### ISSUE TITLE
Horário da prova

### ISSUE THREAD

**Issue by Laurimiguel** [cwi-reset/edicao-04-level-1#354]
Agendei minha prova para determinado horário, tudo ok até aí. Mas agora o horário sumiu e ficou solicitando para marcar outro horário novamente. Espero que não tenha dado nada errado pois o horário que já sumiu, o mesmo que marquei é o único que tenho tempo na sexta.

**Comment by AnaNobre84** [comment]
Acho que deve ser normal, o meu também sumiu, depois que realizei o agendamento

**Comment by Laurimiguel** [comment]
Antes ficava marcado o horário que eu havia escolhido e agora não mostra mais.

**Comment by guilhermewmuller** [comment]
Boa tarde!
A confirmação do agendamento será enviada por e-mail amanhã, juntamente com o link de acesso a prova. Apenas o último registro de agendamento será considerado!
