### ISSUE TITLE
Reset_level_01

### ISSUE THREAD

**Issue by LinuxRenato** [cwi-reset/edicao-04-level-1#36]
Bom dia!!!!
Me chamo Renato Claudino.Trabalho com máquinas elétricas, e sempre foi um sonho aprender programação.
Boa sorte a todos, tamo juntos!!

**Comment by gustavoullmann** [comment]
Oi @LinuxRenato! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
