### ISSUE TITLE
Entrevistas e Pós Prova level 1 

### ISSUE THREAD

**Issue by LucasCBRUM** [cwi-reset/edicao-04-level-1#374]
Não sei se isso foi respondido em vídeo ou em live, mas gostaria de saber como vão funcionar esses dias pós prova level 1, como serão essas entrevistas, como vai funcionar esse período pós prova?

**Comment by danieleataydes** [comment]
Olá @LucasCBRUM!
Receberemos um e-mail no dia 28 com maiores informações. Contudo, há uma FAQ que responde diversas dúvidas > [https://cwi-reset.notion.site/cwi-reset/FAQ-2427e09c26f44da8b19282829ea22377#34268c6499d64dd8a3269e8b8f4e64df](url) e um cronograma junto ao conteúdo (que poderá ou não sofrer alterações). 

Por enquanto seguimos aguardando (:

**Comment by RebecaPR** [comment]
Temos que aguardar o e-mail do dia 28, para saber se passamos ou não pra etapa de entrevistas e ai sim após estas se vamos para o level 2...
Ansiedade a mil até o dia 28!!! 😖😖

**Comment by LucasCBRUM** [comment]
MUITO OBRIGADO GENTE ❤️🥰🚀

**Comment by Alinervit** [comment]
Bom dia pessoal, Tudo bem?

O e-mail de ontem é independente se passarmos ou não? Alguém sabe essa informação?
