### ISSUE TITLE
boa tarde galera, bora resetar 

### ISSUE THREAD

**Issue by Schiavonije** [cwi-reset/edicao-04-level-1#38]
Olá!! Me chamo Jéssica, atualmente sou técnica de enfermagem trabalhando em uma UTI neonatal. Pronta pra migrar para área de TI. Sou apaixonada por games, séries e animes. Vamos nessa juntos, boa missão para nós.

**Comment by gustavoullmann** [comment]
Oi @Schiavonije! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by Schiavonije** [comment]
Ola! Muito obrigada pela orientação, hahahaha opss

Em seg., 29 de ago. de 2022 às 12:45, Gustavo Ullmann <
***@***.***> escreveu:
