### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by melgrando** [cwi-reset/edicao-04-level-1#39]
## Melânia Grando
Sou da área comercial e busco conhecimentos para migrar para área de QA.🚀🚀

**Comment by gustavoullmann** [comment]
Oi @melgrando! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
