### ISSUE TITLE
Primeira missão!

### ISSUE THREAD

**Issue by deisegrasel** [cwi-reset/edicao-04-level-1#40]
Olá galera, me chamo Deise, tenho 26 anos e sou de Venâncio Aires, RS. 
Atualmente trabalho como projetista e vendedora em uma indústria de vidros.
Sou formada em Design pela Univates e estou muuuito ansiosa para me aprofundar no mundo da Ti. 
Bons estudos para todos nós!

**Comment by gustavoullmann** [comment]
Oi @deisegrasel! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
