### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by JeanValentim** [cwi-reset/edicao-04-level-1#42]
Opa, me chamo Jean e sou técnico em Redes. Anos atrás me afastei da área de TI mas o bom filho à casa torna. 
Atualmente sou supervisor educacional e quero voltar pra minha área de origem.
Boraa!!

**Comment by gustavoullmann** [comment]
Oi @JeanValentim! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by JeanValentim** [comment]
Obrigado
