### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by fabiarocha** [cwi-reset/edicao-04-level-1#43]
#43 Boa tarde, me chamo Ana Fábia sou de Campina Grande PB, sou Fisioterapeuta e agora estou migrando para TI, boa sorte a todos.

**Comment by gustavoullmann** [comment]
Oi @fabiarocha! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
