### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by VONFLEBBEW** [cwi-reset/edicao-04-level-1#44]
Eu me Chamo Wladimir L. von Flebbe, estou fazendo transição de carreira, pois, venho da área de Administração de Empresas e Técnico em eletrônica.
Sou aqui de Porto Alegre.
Abraço a todos e ótima jornada para nós!

**Comment by gustavoullmann** [comment]
Oi @VONFLEBBEW! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
