### ISSUE TITLE
Apresentação - Patricia Aires

### ISSUE THREAD

**Issue by PatriciaAires** [cwi-reset/edicao-04-level-1#45]
Boa tarde pessoal! 
Meu nome é Patrícia, tenho 44 anos, Graduada em Administração, trabalhando na área administrativa/financeira há mais de 13 anos, estou notivada para assumir novos desafios onde eu possa adquirir novos conhecimentos com o objetivo de me aperfeiçoar e expandir as minhas opções profissionais. E por isso estou feliz da vida por estar aqui iniciando essa primeira etapa,  rumo ao Reset na minha carreira.

**Comment by gustavoullmann** [comment]
Oi @PatriciaAires! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
