### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by eduardosvelho** [cwi-reset/edicao-04-level-1#46]
😀 Olá, @Pessoal!  Meu nome é Eduardo, tenho 44 anos, sou de Canoas/RS e graduado em Marketing pela UNISUL. Resumidamente, minha experiência é com gestão de marketing e e-commerce, com projetos no varejo de moda e tecnologia e na indústria de alimentação, móveis e decoração de alto padrão. Implementação de metodologias ágeis com foco em desenvolvimento de equipes de alta performance. Criação de projetos de marketing com ênfase em vendas, experiência online e canais, gestão de tráfego e análise  de dados. Apaixonado por e-commerce e um entusiasta por tecnologia, futurismo e UX/UI. Há 2 anos, venho desejando me desafiar em outras áreas, então, estou fazendo uma curva de 180º aqui no Reset e estou muito contente pela oportunidade de desbravar novos conhecimento. Desejo sucesso a todos! 🙌

**Comment by gustavoullmann** [comment]
Oi @eduardosvelho! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by eduardosvelho** [comment]
> 😀 Olá, @Pessoal! Meu nome é Eduardo, tenho 44 anos, sou de Canoas/RS e graduado em Marketing pela UNISUL. Resumidamente, minha experiência é com gestão de marketing e e-commerce, com projetos no varejo de moda e tecnologia e na indústria de alimentação, móveis e decoração de alto padrão. Implementação de metodologias ágeis com foco em desenvolvimento de equipes de alta performance. Criação de projetos de marketing com ênfase em vendas, experiência online e canais, gestão de tráfego e análise de dados. Apaixonado por e-commerce e um entusiasta por tecnologia, futurismo e UX/UI. Há 2 anos, venho desejando me desafiar em outras áreas, então, estou fazendo uma curva de 180º aqui no Reset e estou muito contente pela oportunidade de desbravar novos conhecimento. Desejo sucesso a todos! 🙌
