### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by filipebianconi** [cwi-reset/edicao-04-level-1#47]
Olá pessoal, espero que todos estejam bem!
Me chamo Filipe Bianconi, venho da área de logística, e estou muito empolgado em participar desse projeto maravilhoso. Sucesso a todos!!!

**Comment by gustavoullmann** [comment]
Oi @filipebianconi! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
