### ISSUE TITLE
Olá Mundo!!!

### ISSUE THREAD

**Issue by renatolarrossa** [cwi-reset/edicao-04-level-1#48]
Salve pessoal! 

Muito legal participar dessa baita iniciativa ;)
Sou o Renato Larrossa e venho da área de segurança do trabalho.

**Comment by gustavoullmann** [comment]
Oi @renatolarrossa! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
