### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by pablo-bosak** [cwi-reset/edicao-04-level-1#49]
Boa noite pessoal, espero que todos estejam bem. Eu me chamo Pablo Bosak, tenho 38 anos, moro em Natal, sou formado em Direito, passei um tempo fora morando em Santiago, Chile, trabalhando na área comercial de uma empresa de turismo. Atualmente me encontro em transição de carreira pra área tecnológica, fazendo o curso de Análise e Desenvolvimento de Sistemas. 
Um abraço a todos e uma excelente jornada pessoal. 💪💪👍👍👍

**Comment by gustavoullmann** [comment]
Oi @pablo-bosak! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
