### ISSUE TITLE
Reset 

### ISSUE THREAD

**Issue by 01Lu02** [cwi-reset/edicao-04-level-1#50]
Oi, gente!
Nossa, nem acredito que estamos aqui,
o primeiro passo para a realização de um sonho. 
Me chamo Luíza e atualmente estou no ramo da Logística. Boa sorte pra todos e bons estudos. 👩‍💻🚀

**Comment by gustavoullmann** [comment]
Oi @01Lu02! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
