### ISSUE TITLE
Apresentação Lucia Hoffmann 

### ISSUE THREAD

**Issue by LuciaHoffmann** [cwi-reset/edicao-04-level-1#51]
Olá, tudo bem galera? Aqui quem fala é a Lucia Hoffmann, me apresento dizendo que chorei afu de tão feliz em ser selecionada. Venho da área de atuação comercio/Financeiro e maternidade. Bora aprender e evoluir! Valeu a oportunidade CWI.

**Comment by gustavoullmann** [comment]
Oi @LuciaHoffmann! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
