### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by lailsonnicacio** [cwi-reset/edicao-04-level-1#52]
Boa noite, sou Lailson Nicacio, sou do Rio Grande do Norte, tenho graduação em Engenharia Civil, e atualmente trabalho como temporário no IBGE como supervisor de coleta e qualidade.

**Comment by gustavoullmann** [comment]
Oi @lailsonnicacio! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
