### ISSUE TITLE
Oiii Povo!

### ISSUE THREAD

**Issue by JessySalls** [cwi-reset/edicao-04-level-1#53]
_Me chamo Jéssica, tenho 31 anos, sou pernambucana e moro em Novo Hamburgo/RS. Minha formação é Administração, já fui gestora de hotel, restaurante, no setor calçadista e atualmente atuo como gestora comercial no setor de estética (sim, é muita coisa😅). A TI sempre esteve presente na minha vida de alguma maneira e eu sempre fui fingindo que não tava vendo, mas agora eu decidi que é hora de dar o reset e ir atrás do que eu quero. Vai ser uma jornada massa!_

**Comment by gustavoullmann** [comment]
Oi @JessySalls! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
