### ISSUE TITLE
Partiu Resetar

### ISSUE THREAD

**Issue by Laurimiguel** [cwi-reset/edicao-04-level-1#54]
Boa noite galera.
Me chamo Lauri e sou professor de Educação Física.
Partiu dar um RESET..

**Comment by gustavoullmann** [comment]
Oi @Laurimiguel! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
