### ISSUE TITLE
Apresentação - Camila Goulart 

### ISSUE THREAD

**Issue by CamilaGoulart** [cwi-reset/edicao-04-level-1#55]
Olá pessoal! Me chamo Camila Goulart Rodrigues, tenho 29 anos e busco um reset na carreira. Estou muito feliz com essa oportunidade. Atualmente trabalho com vendas em uma empresa de Epi's para bombeiros. Sou formada em Processos Gerenciais. Trabalho há 10 anos na área do comércio e estou preparada para esse desafio e fazer essa transição para a TI. Vamos aprender juntos!!!

**Comment by gustavoullmann** [comment]
Oi @CamilaGoulart! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
