### ISSUE TITLE
Tem Dev's novos na área Geeente!

### ISSUE THREAD

**Issue by TalesLoran** [cwi-reset/edicao-04-level-1#56]
Olá "serHumaninhos"!

Meu nome é Tales Machado, entrei para o T.I. fazem dois ano (mais ou menos) faço tecnologo em análise e desenvolvimento de sistemas.

Fazem quatro anos que trabalho em um mercado de pequeno porte, literalmente faço de tudo =) .
Estou muito ancioso para crescer e "Resetar" junto com todos vocês.

Desejo muito sucesso a todos.

**Comment by gustavoullmann** [comment]
Oi @TalesLoran! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
