### ISSUE TITLE
[Luiz Silva] Apresentação 

### ISSUE THREAD

**Issue by Luizfernandoal** [cwi-reset/edicao-04-level-1#57]
Bom dia Pessoal!
Sou Luiz Fernando Silva, atuo na área de telecomunicações há 12 anos. Muito feliz pelo amigo Joacy ter me apresentado o programa reset e mais feliz ainda em ter sido selecionado para essa primeira etapa. 

Vamos de reset... Bom trreinamento a todos.

**Comment by gustavoullmann** [comment]
Oi @Luizfernandoal! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
