### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by eukarolinebrito** [cwi-reset/edicao-04-level-1#6]
Olá, pessoal. Me chamo Karol e tenho 21 anos, sou graduanda do 1° semestre de Análise e Desenvolvimento de Sistemas, venha da área administrativa hospitalar, agradeço a CWI pela oportunidade de ter o reset na minha carreira.

**Comment by Grazi-Lg** [comment]
Olá, me chamo Grazi tenho 39 anos vim do ramo comercial e atualmente busco oportunidade de crescimento na área de tecnologia, me considero muito curiosa e comunicativa facilitando assim o aprendizado. Tenho grande expectativa nesta nova etapa da minha vida, gosto muito de tecnologia e estou feliz em poder começar uma nova carreira.

**Comment by fabianaRusso** [comment]
Olá pessoal! Me chamo Fabiana, tenho 34 anos sou do interior de SP, venho da área de Marketing estou tentando iniciar na tecnologia e estou muito grata por essa oportunidade, de fazer parte desse programa CWI Reset, super ansiosa para os desafios que irei enfrentar. Espero criar conexões por aqui, bora comunidade vamos se ajudar.

**Comment by AndersonAJO** [comment]
É isso aí pessoal me chamo Anderson José de Oliveira venho da área de Gestão da Produção e estou bem animado em dar um #Reset na minha carreira juntamente com todos vocês e o pessoal da CWI, vamos que vamos.

**Comment by gustavoullmann** [comment]
Oi @eukarolinebrito, @fabianaRusso, @AndersonAJO! Sejam bem vindos!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
