### ISSUE TITLE
Oportunidade de uma vida! 

### ISSUE THREAD

**Issue by Toncgpb** [cwi-reset/edicao-04-level-1#60]
Muito feliz por ter essa oportunidade! Me chamo José Emirton Leite Silva, venho de uma carreira dentro de fábrica têxtil. Em 2016 concluí meu primeiro curso  de ADS, mas acabei não trabalhando na área, hoje estou cursando Engenharia de Software e vou dar um RESET literalmente na minha vida profissional; quero escrever uma grande história nessas novas páginas da minha vida.

**Comment by gustavoullmann** [comment]
Oi @Toncgpb! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
