### ISSUE TITLE
[Apresentação] [Jéssica Cunha] Hello!

### ISSUE THREAD

**Issue by cunhajessica** [cwi-reset/edicao-04-level-1#61]
Fala, pessoal!

Me chamo Jéssica da Silva Cunha, atualmente estou na área do Comércio Exterior e animada pra dar um **Reset** na vida.
Ansiosa pra começar essa jornada!
Bora "Resetar"! \o
Bons estudos a todos!

**Comment by gustavoullmann** [comment]
Oi @cunhajessica! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
