### ISSUE TITLE
Apresentação - Steve Jimenez!

### ISSUE THREAD

**Issue by Jimenez09** [cwi-reset/edicao-04-level-1#62]
Meu nome é Steve Jimenez, profissional com 13 anos de experiência na indústria calçadista e 6 anos na área de segurança patrimonial onde trabalho atualmente, estou muito feliz por estar nessa etapa!!!

**Comment by gustavoullmann** [comment]
Oi @Jimenez09! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
