### ISSUE TITLE
Thankyou CWI

### ISSUE THREAD

**Issue by MarcioTomazoni** [cwi-reset/edicao-04-level-1#64]
Bom dia. Me chamo Marcio Tomazoni sou líder de equipe de uma praça de pedágio na serra gaúcha. Queria agradecer imensamente à CWI pela oportunidade que me foi dada e dizer que estou ansioso para iniciar nessa jornada. Desejo boa sorte a todos os participantes do Reset... and let's code together!

**Comment by gustavoullmann** [comment]
Oi @MarcioTomazoni! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
