### ISSUE TITLE
Gratidão CWI

### ISSUE THREAD

**Issue by faustopb** [cwi-reset/edicao-04-level-1#66]
Me chamo Fausto estou tão feliz com esta oportunidade da **CWI** que me deixou muito feliz!!!

**GRATDIÃO É O QUE RESUME ESTE MOMENTO**

**Comment by gustavoullmann** [comment]
Oi @faustopb! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
