### ISSUE TITLE
Hello, World! [Apresentação: "Matheus Marques"]

### ISSUE THREAD

**Issue by matheus258** [cwi-reset/edicao-04-level-1#71]
**Olá pessoal, tudo bem?**

Passando aqui para agradecer a oportunidade, e esforço da equipe para entregar conteúdos de qualidade excelente.

Me apresentando brevemente, tenho 23 anos e atuo no mercado de atendimento ao cliente em restaurantes. Atualmente estou cursando Ciência da Computação, e amo muito tecnologia.

**Comment by gustavoullmann** [comment]
Oi @matheus258! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
