### ISSUE TITLE
Cris Sá 

### ISSUE THREAD

**Issue by Crisreginasa** [cwi-reset/edicao-04-level-1#72]
Me chamo Cristiane , sou técnica em enfermagem e este é meu primeiro contato com TI. Gratidão a CWI por essa oportunidade em dar um reset na carreira.

**Comment by gustavoullmann** [comment]
Oi @Crisreginasa! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
