### ISSUE TITLE
Apresentação.

### ISSUE THREAD

**Issue by marlonAntony** [cwi-reset/edicao-04-level-1#74]
Olá, chamo-me Marlon, tenho 28 anos e sou natural e residente de Novo Hamburgo, atualmente trabalho na área de logística e espero dar um reset em minha carreira.

**Comment by gustavoullmann** [comment]
Oi @marlonAntony! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
