### ISSUE TITLE
Apresentação Cíntia 

### ISSUE THREAD

**Issue by cintiatraesel** [cwi-reset/edicao-04-level-1#75]
Olá sou a Cíntia, sou professora e sempre gostei muito de tecnologia, meu noivo já trabalha na área, acompanho às vezes o trabalho dele, estou muito feliz pela oportunidade de dar um reset na minha carreira.

**Comment by gustavoullmann** [comment]
Oi @cintiatraesel! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
