### ISSUE TITLE
Olá boa tarde! Me chamo Ana Paula, estou no segundo semestre de Análise e Desenvolvimento de Sistemas e claro muito feliz em poder estar aqui.

### ISSUE THREAD

**Issue by ArunaADS** [cwi-reset/edicao-04-level-1#77]

**Comment by gustavoullmann** [comment]
Oi @ArunaADS! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by ArunaADS** [comment]
Boa noite Gustavo..
Sim, o fiz após, acho que fiquei tão emocionada que coloquei antes
hahahahah..
Mas muito obrigada por me enviar o link.
Abraço!

Em seg, 29 de ago de 2022 13:07, Gustavo Ullmann ***@***.***>
escreveu:
