### ISSUE TITLE
AHHHH !!! EU TO NO RESET !!!!!

### ISSUE THREAD

**Issue by LauraSGaspar** [cwi-reset/edicao-04-level-1#78]
Fala galera !!!
Sou a Laura e estou mega feliz por estar no RESET, venho do comercio, como atendente de farmacia. Nao vejo a hora de dar aquele RESET na vida. Obrigado CWI pela oportunidade

**Comment by gustavoullmann** [comment]
Oi @LauraSGaspar! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
