### ISSUE TITLE
Apresentação Bruna -  Obrigada CWI - RESET!!

### ISSUE THREAD

**Issue by brunafmonique** [cwi-reset/edicao-04-level-1#79]
Olá pessoal, muito feliz por estar no programa RESET! Obrigada CWI pela oportunidade!
Me chamo Bruna, sou formada em Publicidade e trabalho como Social Media e Marketing Digital. Ansiosa para dar uma RESET na carreira! Boraaa!!

**Comment by gustavoullmann** [comment]
Oi @brunafmonique! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
