### ISSUE TITLE
[DÚVIDA] Qual é o link para a live de 19h?

### ISSUE THREAD

**Issue by joaofmds** [cwi-reset/edicao-04-level-1#80]
Olá, qual é o link para a live de hoje às 19h?

**Comment by joaofmds** [comment]
Para quem não encontrou, segue: https://vimeo.com/event/2380359/045316df40

**Comment by biateisi** [comment]
Obrigada João! :)

Todas as lives estarão sempre disponíveis para assistirmos depois, ou apenas durante a transmissão?

**Comment by Renatalealmoreira** [comment]
Olá @biateisi as lives ficam gravadas, você pode assistir depois.

**Comment by Allemaun** [comment]
@biateisi 
Mesmo que fiquem gravadas acredito ser muito importante assistir ao vivo, pois com certezas frequência vai contar bastante nas avaliações.

**Comment by Catia-cyber** [comment]
> Obrigada João! :)
> 
> Todas as lives estarão sempre disponíveis para assistirmos depois, ou apenas durante a transmissãoper?

irão ficar disponíveis sim

**Comment by isaquexavier1155** [comment]
Nem todos conseguem assistir a live ao vivo então acredito que a gravação ficará disponível sim.

**Comment by 89anderson** [comment]
Boa tarde galera, todos bem?

As lives ficarão gravada sim! Podem ficar tranquilos! :)

Quem puder, apareça no horário da live, a interação entre a galera é sempre muito legal e divertida.

Bora pra cima 🚀

**Comment by Ronaldoluizsilva** [comment]
https://vimeo.com/event/2380359/045316df40
segue

**Comment by deniscoelho-js** [comment]
Obrigado, vim conferir se alguém tinha postado.

**Comment by MateusNeres26** [comment]
boa noite, onde acharam este link? pq não recebi nada

**Comment by JessySalls** [comment]
Gente, alguém sabe como faço para acessar a live gravada? Acesso o link e não consigo achar 😔
As próximas já estou organizada pra assistir ao vivo, mas hoje realmente não conseguia entrar.

**Comment by diegorafaelvieira** [comment]
Logo mais vamos receber um e-mail com o link da gravação.

**Comment by isaquexavier1155** [comment]
Fiquem de olho nos seus emails. Logo receberão o link da gravação da aula.

**Comment by 89anderson** [comment]
Boa tarde pessoal, todos bem?
Vocês devem receber no email que utilizaram para a inscrição, um link para assistir a live gravada.
Junto com este link, vocês devem receber um formulário para avaliar o conteúdo abordado.

O prazo para que vocês recebam o link da primeira live é até quarta feira!

Dúvidas, estou a disposição para auxiliá-los.

**Comment by sarahpedroso** [comment]
Olá, boa tarde, pessoal! Tudo bem?
Estou com dificuldade em entender sobre o que foi falado na live dos canais de comunicação e, mais especificamente sobre o Discord.
Infelizmente não consegui participar da live ao vivo, mas assisti hoje e fiquei sem entender, pois não recebi nenhum link para entrar num grupo específico no Discord, e quando entro no site, ele pede um link de convite para acessar ao servidor existente.
Caso alguém possa me ajudar, ficarei imensamente grata!
Muito obrigada.

**Comment by 89anderson** [comment]
> Olá, boa tarde, pessoal! Tudo bem? Estou com dificuldade em entender sobre o que foi falado na live dos canais de comunicação e, mais especificamente sobre o Discord. Infelizmente não consegui participar da live ao vivo, mas assisti hoje e fiquei sem entender, pois não recebi nenhum link para entrar num grupo específico no Discord, e quando entro no site, ele pede um link de convite para acessar ao servidor existente. Caso alguém possa me ajudar, ficarei imensamente grata! Muito obrigada.

Boa tarde Sara, tudo joia?

Na live foi proposto que os estudos e as discussões do level 1 sejam feitos diretamente aqui no Github. Isso porque temos uma grande quantidade de participantes e, com a utilização das issues do Github, nós monitores conseguimos ser mais rápidos e assertivos para auxiliar vocês. Alem disso, a dúvida de um pode ser a dúvida de muitos, e com isso conseguimos atingir uma quantidade maior de pessoas de um jeito mais dinâmico.

Utilizaremos do discord como canal oficial do reset na segunda fase apenas.

Os canais de discord, telegram e whatsapp que foram criados durante o level 1 foram feitos pelos participantes do level 1.

Qualquer dúvida, estamos a disposição para auxiliá-los.
