### ISSUE TITLE
Apresentação Camila Sampaio

### ISSUE THREAD

**Issue by MilaSampaio** [cwi-reset/edicao-04-level-1#81]
Olá, me chamo Camila Sampaio tenho 29 anos e atualmente trabalho na área administrativa hospitalar.  Estou muito feliz com a oportunidade e que venham os desafios!

**Comment by gustavoullmann** [comment]
Oi @MilaSampaio! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by MilaSampaio** [comment]
Oi, muito obrigada!
