### ISSUE TITLE
[Início] [Primeira Missão CWI] - Apresentação Inicial- Manu

### ISSUE THREAD

**Issue by EmanuelleT** [cwi-reset/edicao-04-level-1#83]
Sou a Emanuelle a trabalho em um empresa de energia elétrica. Estou pronta para dar um RESET, RESTART and GO!! Vlw CWI pela iniciativa.

**Comment by gustavoullmann** [comment]
Oi @EmanuelleT! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
