### ISSUE TITLE
Olá

### ISSUE THREAD

**Issue by maiconramosdevs** [cwi-reset/edicao-04-level-1#84]
Me chamo Maicon Ramos. Sou servidor público e médico veteriário formado a 5 anos. Feliz com a oprtunidade que a CWI está proporcionando.

**Comment by gustavoullmann** [comment]
Oi @maiconramosdevs! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
