### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by sldanisl** [cwi-reset/edicao-04-level-1#86]
Olá

Me chamo Daniela , expectativa enorme com essa nova oportunidade milhões de possibilidades.
Atuo a mais de 12 anos com gestão de equipe e administração de serviços. Partiu RESET !!!!!

**Comment by gustavoullmann** [comment]
Oi @sldanisl! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
