### ISSUE TITLE
Reset. 

### ISSUE THREAD

**Issue by Maiconpontel** [cwi-reset/edicao-04-level-1#88]
Meu nome é Maicon Pontel sou profissional de Educação Física a 10 anos e estou ansioso em migrar para esse novo desafio.

**Comment by luizguilhermez** [comment]
Luiz Guilherme...presente...

**Comment by gustavoullmann** [comment]
Oi @Maiconpontel, @luizguilhermez ! Sejam bem vindos!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
