### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by AntonioFariaVieira** [cwi-reset/edicao-04-level-1#89]
Olá! Me chamo Antônio Vieira, sou empresário e estou ansioso para aprender com todos!

**Comment by gustavoullmann** [comment]
Oi @AntonioFariaVieira! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by AntonioFariaVieira** [comment]
Obrigado, Gustavo! Já enviei a apresentação no link correto, só não tinha conseguido apagar essa! Abraço
