### ISSUE TITLE
APRESENTAÇÃO!!!!!

### ISSUE THREAD

**Issue by Jessisouza25** [cwi-reset/edicao-04-level-1#90]
Good Evening People!!

Vamos com tudo!!! Sucesso para todos nós!!

 Me chamo Jéssica e venho da área Comercial!! Vamos com força total!!!! 

Gratidão CWI por esta oportunidade!!!

**Comment by gustavoullmann** [comment]
Oi @Jessisouza25! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
