### ISSUE TITLE
Apresentação!!!

### ISSUE THREAD

**Issue by Samara73** [cwi-reset/edicao-04-level-1#91]
Helloooooooo!!!!!!

Meu nome é Samara Alicia, tenho 24 anos, sou formada em Matemática, trabalho como freelancer dando aulas particulares e sou servidora pública municipal na área da saúde.
Adorei a oportunidade oferecida pela CWI e estou pronta para dar um **#Reset** na minha carreira!!!

**Comment by gustavoullmann** [comment]
Oi @Samara73! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
