### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by WeversonJAlves** [cwi-reset/edicao-04-level-1#92]
Opa! Me chamo Weverson, venho da área comercial, hoje trabalho com comprador em uma loja de materiais elétricos.
Estou ansioso com esta nova oportunidade, boa sorte a todos!

**Comment by gustavoullmann** [comment]
Oi @WeversonJAlves! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
