### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by FernandaFFerreira** [cwi-reset/edicao-04-level-1#94]
Olá pessoal, 
Me chamo Fernanda, tenho 23 anos de idade, sou de Anápolis-GO. Estou muito feliz por ter essa oportunidade no RESET.
Venho atuando na área ADM. Fiscal/Finanças a 6 anos e chegou a hora de resetar na minha carreira. :D

**Comment by gustavoullmann** [comment]
Oi @FernandaFFerreira! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
