### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by JMSantos1985** [cwi-reset/edicao-04-level-1#97]
Meu nome é Jonatas, estou muito feliz  com esta oportunidade, valeu CWI. 
Vamos pra cima!!

**Comment by gustavoullmann** [comment]
Oi @JMSantos1985! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
