### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by antoniapires** [cwi-reset/edicao-04-level-1#98]
Bom dia a todos!!! Sou Maria Antônia, Engenheira Agrícola, tenho 53 anos e estou muito feliz em ter sido selecionada para este treinamento, aliás um processo que configura um imenso desafio pessoal e profissional, pelo menos paramim.

**Comment by gustavoullmann** [comment]
Oi @antoniapires! Seja bem vinda!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:

**Comment by antoniapires** [comment]
Oi Gustavo, recebi o e-mail e refiz a apresentação no link indicado!!!
