### ISSUE TITLE
[ Inicio / 1-Missão CWI ] Apresentação/Adriano-Arruda

### ISSUE THREAD

**Issue by Adtrn** [cwi-reset/edicao-04-level-1#99]
Olá galera tudo Joinha com vocês  ; )   estou muito Feliz por tal oportunidade de Aprendizagem ,compartilhamento dentro da comunidade CWI. Parabéns aos idealizadores e colaboradores bora la codar um cadinho.

**Comment by gustavoullmann** [comment]
Oi @Adtrn! Seja bem vindo!
A issue que está sendo utillizada para a apresentação é esse link: https://github.com/cwi-reset/edicao-04-level-1/issues/1

Bons estudos :rocket:
